### ISSUE TITLE
Display results with diff / show-all

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#105]
To get an overview `mutmut show-all` would be useful, which would basically be `mutmut results` with `mutmut show` for each result.

`mutmut results -v` might be good for this, but when looking into it (the source) I've noticed that it is still not using click properly.. ;)

**Comment by boxed** [comment]
I've thought about doing `mutmut show all` but it's only really useful if you have a very small number of mutants.

>  I've noticed that it is still not using click properly.. ;)

Yea, I gave it a shot once and I couldn't get it to work, so I punted on it.

**Comment by blueyed** [comment]
> I've thought about doing `mutmut show all` but it's only really useful if you have a very small number of mutants.

Not really - even with a long list, it is useful for an overview etc (you can pipe it to `less` etc).

**Comment by boxed** [comment]
Well ok then.. I'll add a warning though that the way mutmut produces diffs is super slow, so if you have lots of mutants it might not be very fun to do this :P

**Comment by boxed** [comment]
Just tried this on a project at work, the trivial implementation took 46 seconds for 181 mutants. I'd be nice to optimize that at some point :P

**Comment by boxed** [comment]
Added `mutmut show all path/to/file.py` because I wanted it :)

**Comment by ryanfreckleton** [comment]
This option needs to be documents.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
