### ISSUE TITLE
mutmut show: display status

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#106]
`mutmut show X` should also display the status of the mutant.
This should be done in a way to have the output still be a valid patch, but that means to just prepend it at the top, maybe à la "# mutant status: …".

This is related to #105 a bit.

**Comment by boxed** [comment]
Maybe just print out a warning if you show a non-surviving mutant? Since you're probably making a mistake at that point.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
