### ISSUE TITLE
Improve docs/Add examples

### ISSUE THREAD

**Issue by mqueiroz1995** [boxed/mutmut#109]
The documentation is not covering all functionality and doesn't have a lot of examples, so after a lot of struggle, I'm still not able to run it successfully. 

My dir structure is the following:
```
/project
    /src
    /tests
```

I have a simple example class and test class: 

```python
class Example:

    def __init__(self):
        pass

    def is_bigger_than_5(self, a):
        return a > 5
```

```python
import unittest
from ..src.Example import Example


class ExampleTest(unittest.TestCase):

    def test_is_bigger_than_5(self):
        example = Example()
        self.assertFalse(example.is_bigger_than_5(3))

if __name__ == "__main__":
    unittest.main()
```
The testing framework I'm using is **unittest**, so my `setup.cfg` is the following:

```cfg
[mutmut]
runner=python -m unittest 
```

After running the tool from `/project` dir the mutations are generated, but all of them fail like this:

Mutant #3
**no-testclass**
Time Taken: 0.0s
Failed: bad_survived

If I introduce the same bugs to the codebase manually the tests fail. This and the **no-testclass** makes me think that the tests are not running at all, and I searched a lot how to setup properly without success.

**Comment by boxed** [comment]
Could you post a zip file of that project? Describing it doesn't make much sense to me. That relative import looks broken for example.

The output you describe also doesn't make sense, that's not mutmuts output. 

Do you run exactly "python -m unittest" from the same directory you run mutmut from and it runs one test?

**Comment by mqueiroz1995** [comment]
Fixed the points mentioned and it is working. Thank you 😄

It is not mutmuts output because I'm running on windows command prompt which doesn't support emojis.

![anaconda-prompt](https://user-images.githubusercontent.com/16572913/55288980-a0abc400-53dd-11e9-84cc-1fe524cc778e.png)

So I'm exporting as XML and them converting to HTML using [JUnit2HTML](https://gitlab.com/inorton/junit2html). Maybe the exported format is not fully compatible or the error is in the other tool.

I'm leaving the sample project here. It can serve as a base to create examples or as a reference to other unittest and windows users.

[project.zip](https://github.com/boxed/mutmut/files/3026566/project.zip)

**Comment by boxed** [comment]
I didn't realize windows was that far behind! Maybe I'll look at that. 

In any case you should use `mutmut results` instead of all that complicated stuff, it works fine and has plain text explanations.
