### ISSUE TITLE
Be more verbose

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#11]
There should be some output when running `mutmut` by default.

I am just trying it out (seen it via https://github.com/tarpas/pytest-testmon/issues/76), but it seems to be very silent during the initial run for example.
It would be nice to just get the normal output there - which should include wrapping in pytest-sugar if it is installed/enabled.

**Comment by boxed** [comment]
There's a flag "-s" to stop capturing output from child processes. 

Why do you think it's needed though? I've run it like this in earlier versions of mutmut and it was quite useless. If the initial run fails I print the output from that, that's the only thing that makes sense from my experience.

**Comment by boxed** [comment]
I'm closing this for now, as I currently disagree based on having run mutmut on several code bases.

**Comment by blueyed** [comment]
I came here to ask for this again.

I've just tried it on pytest's source with `mutmut -s --show-times src/_pytest/compat.py`, but there's not output after a few minutes still.  It would be good to know what is going on.

I see output with `mutmut -s --show-times --runner 'python -m pytest testing/test_collection.py' src/_pytest/compat.py` though, so it seems like with the default runner it is either taking too long (does it only output after a first complete run?), or something else is off.

**Comment by boxed** [comment]
Yes it only outputs after the initial run is complete. Mutation testing is for the patient :P 

Just dumping all output through to stdout/stderr would drown mutmuts own output. This is less of a problem now because of the `--print-cache` option though, so this can be reopened.

**Comment by boxed** [comment]
What kind of output would you like to see? Just some indeterminate spinner or..?

**Comment by blueyed** [comment]
I think the fix in https://github.com/boxed/mutmut/commit/6370bd06b521906fa8cc513d51f9dbe59240746a is good enough here already, i.e. it now displays that it is doing the initial run.

Thanks!
