### ISSUE TITLE
Speed expectations

### ISSUE THREAD

**Issue by piccolbo** [boxed/mutmut#110]
Just running mutmut for the first time on my project altair_recipes. tests pass in 90 secs. mutmut has been running for a few hours, shows ⠧ 320/522  🎉 274  ⏰ 0  🤔 0  🙁 46 , still working.
Run at defaults with pipenv run (since tests run with pipenv run as well). Anything I am doing wrong, things I should check? It can't normally be this slow. OS X high sierra, python 3.7. Thanks

**Comment by boxed** [comment]
90 seconds * 522 is 13 hours, so if many tests don't fail very fast that's what you're looking at unfortunately. The best scenario is to try to make the tests faster, run on a subset of the code at a time, or just leaving it over night.

Note though that you can look at the results you have thus far at any time in a separate console with `mutmut results` _while it's running_. And you can ctrl+c and it will remember your state, so if you restart it will jump to 320/522 (or whatever) directly if the code and tests are unchanged.

**Comment by blueyed** [comment]
Make sure to use e.g. `-x` with pytest to not run the tests always, but stop at the first failure.

**Comment by blueyed** [comment]
Also `pipenv` is rather slow, so I would look into using e.g. `..venv/bin/python -m pytest` directly.

**Comment by piccolbo** [comment]
Thanks @boxed, now I understand better. It finished overnight. The final tally is  🎉 433  ⏰ 0  🤔 2  🙁 87. What run time triggers the classification as suspicious? I am not sure I follow your argument, even the 433 killed mutants could take much longer to fail than wild type tests take to succeed, right? 

@blueyed Thanks but I only run pipenv run -- mutmut run from top level of the package. pipenv is invoked once and amortized over a night of work, and in any event it is necessary for testing, not optional. As far as using the -x option, that's something mutmut should do right? Or is it under the user control? I woud guess the --runner option, but I can't find any docs.

**Comment by blueyed** [comment]
It uses `-x` by default with pytest.

**Comment by boxed** [comment]
Timeout is 10 times longer to run the tests than the base line. Suspicious is faster than that but still seems like it took significantly more time. It's sort of a guess that the mutation killed a performance optimization.
