### ISSUE TITLE
dunder_whitelist is line based, not AST based, causing unnecessary mutations

### ISSUE THREAD

**Issue by piccolbo** [boxed/mutmut#112]
I examined some of the  mutants that survived (proj altair_recipes) and some of them are just changes in the contents of the `__all__` special variable. I am not sure it should be special cased, but it seems like it is (there's a variable called dunder_whitelist which seems to be meant for that). Is this expected behavior? Is there a workaround without adding too many # pragmas? Thanks

**Comment by boxed** [comment]
Aha. I think that should be a special case. Not sure if I should just whitelist it or do something more sinister like `__all__ = []`. Probably whitelist in the dunder_whitelist is fine as you guessed.

**Comment by boxed** [comment]
Are you ok with ignoring these now or is this hurting your workflow too bad? I usually try to batch up a few fixes between releases...

**Comment by piccolbo** [comment]
I am just kicking the tires, please do not fast track anything because of me. It just adds a bit of noise to the output, that's all (pun intended). It creates one mutant for every `__all__` element, they all survive,  and despite my best attempts to keep APIs small, there's quite a few of them.

**Comment by boxed** [comment]
You can also add pragma no mutant with a regex on all files and not check those changes in, for now.

We do have another ticket for a general system to add custom whitelisting but we haven't come to a conclusion there. Your point of view and experience would be welcome.

**Comment by boxed** [comment]
Ah, I see the problem now.. The whitelist for dunder-symbols is based on lines only, and you've written it like

```python
__all__ = [
    'foo',
    'bar',
]

So I don't match the rule.

**Comment by piccolbo** [comment]
Good catch! But it isn't my quirky formatting, it's straight out of the
black formatter. You're going to see more of that, I'm afraid.

**Comment by piccolbo** [comment]
I installed from master a minute ago and I still see the problem:

```
--- altair_recipes/__init__.py
+++ altair_recipes/__init__.py
@@ -15,7 +15,7 @@
 
 # alphabetically ordered exports
 __all__ = [
-    "autocorrelation",
+    "XXautocorrelationXX",
     "autoplot",
     "barchart",
     "boxplot",

--- altair_recipes/__init__.py
+++ altair_recipes/__init__.py
@@ -16,7 +16,7 @@
 # alphabetically ordered exports
 __all__ = [
     "autocorrelation",
-    "autoplot",
+    "XXautoplotXX",
     "barchart",
     "boxplot",
     "layer",

```
Suggestions?

**Comment by boxed** [comment]
I'll have to take a look at your code base specifically I guess. Thanks for reporting this!

**Comment by boxed** [comment]
I had some problems getting the tests for altair_recipes to run. Just running `tox -e py36` gives me `ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/Users/andersh/Projects/altair_recipes/requirements_dev.txt'`

**Comment by boxed** [comment]
I think I fixed it actually. I just rewrote the handling of the dunder whitelists because it was crazy slow, and it looks like this fixed your use case. Give the new code on master a try!

**Comment by piccolbo** [comment]
All clear now, thanks!

As to testing, you can test with make test. There is no requirements.txt because I am using pipenv, so the Pipfile covers that. mutmut run seems to just work for me. Moot at this point.

**Comment by boxed** [comment]
Good news!

I'm actually asking about the tests for another tool I'm writing that I want to be able to auto detect how to run tests and other things in all projects: https://github.com/boxed/p It's a slow moving project unfortunately...
