### ISSUE TITLE
Whitelist raw-style docstrings

### ISSUE THREAD

**Issue by bskinn** [boxed/mutmut#114]
I use Sphinx autodoc for most of my projects, and often end up with escaped characters in my docstrings. For readability, and due to (I think) flake8 default policies, any docstrings with backslashes are recommended to be set as raw strings (e.g., `r""""foo""""`).

mutmut mutates these r-docstrings to plain docstrings, and finds them as false positives. I definitely see the value of the r-string-to-plain-string mutation in general, but it seems like docstrings should always be exempted/whitelisted from this change, if this makes sense from the development side.

**Comment by boxed** [comment]
Agreed. This is a bug.

**Comment by boxed** [comment]
Thanks for the bug report. I've fixed it, but haven't released a new version yet.

**Comment by bskinn** [comment]
Absolutely! Thanks for a super- quick fix! I can always just pip install the repo until the new release.

mutmut has already pointed towards some interesting potential problems in one of my small projects...in the larger one I tried it on, this bug gave me a somewhat prohibitive number of these false positives. I'm looking forward to trying it again with this noise filtered out.

**Comment by boxed** [comment]
Great to hear! Be sure to blog or tweet and spread the word :P

And of course if you have any more issues post them and we'll probably be able to fix them.
