### ISSUE TITLE
CLI "mutmut ..." commands don't work on Windows

### ISSUE THREAD

**Issue by bskinn** [boxed/mutmut#115]
The simple `$ mutmut ...` invocations work fine on my Debian stretch box, but don't work at all on Windows, giving 'command not found' type errors. `python -m mutmut ...` works fine, though.

Is there any reason `mutmut` isn't using the [`console_scripts` setuptools entry point](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) for the CLI invocations? If not, I'd like to put together a PR to set that up...AFAIK it *should* work uniformly on all platforms. 

Alternatively, I'd propose creating a new `mutmut.bat`, adapted from & to put alongside the current `/bin/mutmut`, to enable streamlined Win CLI invocations.

**Comment by boxed** [comment]
That would be great!
