### ISSUE TITLE
Missing coverage on assignment operators

### ISSUE THREAD

**Issue by borgmanJeremy** [boxed/mutmut#124]
Arithmetic assignment operators like  +=, -=, &=, '>>=' etc should have a mutation that replaces them with the simple assignment operator '='.

It's common when working on microprocessors to add and remove bit flags by using these operators. A common mistake is to accidentally use = instead of |= part way through calculating a register value which will override the existing flags. Often unit tests miss this type of issue because they only test setting 1 bit at a time. If this mutation is added it will let the test author know about this missing case.

I attempted to add this in __init__.py, but I do not think it will be straightforward to have multiple overloads on one operator.

**Comment by boxed** [comment]
You're correct. Mutmut supports only one mutation per mutation point. Maybe just switching the current mutation to what you suggested would be fine. I don't have a strong opinion. Mostly the current choices are wild guesses but you clearly have a strong case for what would be a good mutant!

**Comment by felixdivo** [comment]
Isn't this fully implemented by #129 (and this issue can therefore be closed)?

**Comment by boxed** [comment]
You're right. Thanks for noticing.
