### ISSUE TITLE
Prioritize Mutations: Execution order could be much improved

### ISSUE THREAD

**Issue by maxwellmckinnon** [boxed/mutmut#126]
Are there any plans to use a heuristic or even ML to better order the mutations attempted?

After trialing mutmut, I found that it took a few hours just to get through mutating all the single source constants at the top of the file (who cares), but took much time to triage through all the non-issues found, all of which is wasted time and failures no one would ever care about.

I assume much of my dismay is user error. Are there any best practices beyond the initial getting started guide toward getting the most out of mutmut? Given the runtime and extremely low ratio of important issues to noise, it's hard to justify using this. Even though it's better than coverage in some ways, it's more than 100x more expensive because of all the non-issues to triage through to find a real issue. (Also it's 100x more expensive to to run, but who cares, parallelize or don't run it often). Would be great to prioritize the mutations as well as combine this with testmon, prediction heuristics/ml, or some other tools to better prioritize mutating the pieces that matter first. This would bring the ROI of this tool way up.

I am in love with the idea and would love to see some usability of it improved! After giving it a go on an entire repo as well as several small files, I'm sold on the idea but not sold on the execution. I didn't get anything useful from it. Maybe I'm missing something, maybe just some more info in the top level readme to get going is needed?

Let me know if I can help in any way or if you have suggestions for me to try :)

**Comment by blueyed** [comment]
There is (some) support for testmon already.  If you use `--testmon` the test run should be faster in general (it copied the testmon data back and forth).
Note however, that pytest-testmon has some severe issues when used with `-x` currently (but there are PRs for this already, and I could push my local, combining branch for this).

**Comment by boxed** [comment]
Is the source for your test project available? Your experience seems to radically differ from mine. I have achieved zero mutation score for a few libraries (admittedly small) and I have a very low ratio of whitelisted lines. 

That being said there is also an open issue about having configurable whitelist but we haven't moved forward for lack of some really compelling examples. Maybe your project is exactly this example were looking for where we can see what can work in practice?

**Comment by boxed** [comment]
Closing due to lack of feedback.
