### ISSUE TITLE
Too many string-related errors

### ISSUE THREAD

**Issue by GoldsteinE** [boxed/mutmut#138]
There is a lot strings like
```python
self._log.error("Some debug message with %s", value)
```
I only care about value present in log message (if I care at all), not about log message format. It would be redundant to make assertions about whole log message. So, when mutmut changes this to 
```python
self._log.error("XXSome debug message with %sXX", value)
```
tests doesn't fail. And shouldn't.

I propose adding option not to mutate strings with len() < threshold, because it's possibly human-readable messages which shouldn't be tested.

**Comment by GoldsteinE** [comment]
And it would be cool to have ability to completely exclude all calls of specific function (e. g. `self._log.debug()`) from mutation

**Comment by boxed** [comment]
Yes, we're discussing this and related issues in #47

**Comment by boxed** [comment]
Closing this in favor of #47
