### ISSUE TITLE
UTF-8 emoji icons fail to display in a Pycharm 2019.2.1 terminal in windows

### ISSUE THREAD

**Issue by nklapste** [boxed/mutmut#144]
This was created on a windows 10 environment with Pycharm 2019.2.1.

Running mutmut in the Pycharm native terminal fails to render the emojis indicating killed 🎉, suspicious 🤔, and surviving 🙁 mutants.

For example:
```console 
(venv) >mutmut run --paths-to-mutate my_project

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
� Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
� Suspicious.       Tests took a long time, but not long enough to be fatal.
� Survived.         This means your tests needs to be expanded.

mutmut cache is out of date, clearing it...
1. Running tests without mutations
...
```

Maybe we should simply adopt a ASCII text based notation?

**Comment by boxed** [comment]
We should rather report a bug to PyCharm. The emojis are a big part of why mutmut is instantly intuitive.

**Comment by cmarqu** [comment]
FWIW, I'm on an oldish Red Hat 6 system where both xterm and gnome-terminal also have a (slightly different) problem with some of the emojis.
Maybe instead of 
⠙ 70/70  🎉 53  ⏰ 0  🤔 4  🙁 13
it could be 
`70/70    \o/ 53    -->| 0    :-? 4    :-( 13`
with some coloring for us stuck with inferior environments?

**Comment by boxed** [comment]
If we can figure out if we're running in a busted terminal easily I can accept it, but I really don't like having hacks or worse UX just to handle some bugs/old cruft in other programs.

**Comment by I0x4dI** [comment]
![image](https://user-images.githubusercontent.com/17100854/71765113-1d4a7080-2f23-11ea-92f6-63383f709634.png)
I have a similar problem on Kubunt 18.04. The output of the program is unreadable.

**Comment by boxed** [comment]
@I0x4dI in a normal terminal window? Stock install?

**Comment by I0x4dI** [comment]
> @I0x4dI in a normal terminal window? Stock install?

Yes, in Konsole (KDE terminal).
Yes, install with pip.

**Comment by boxed** [comment]
Sorry, I meant stock install of the OS. You haven't changed the font in the console app?

I would recommend reporting this issue to KDE otherwise.

**Comment by boxed** [comment]
That being said maybe there could be a workaround. It would be nice if we could figure out if we are running in such a crippled environment.

**Comment by Zac-HD** [comment]
I just get a straight-up crash on windows :cry: 

I love the icons, but it would be nice to have a fallback available!

**Comment by boxed** [comment]
Ok. I'm convinced an option is in order. Let's brain storm the display. The point of the emoji are to make the normal mutation testing nomenclature instantly understandable. I want a text only alternative. 

Japanese emoticons have the required range I think but might be harder to understand. Whst do you guys think?

**Comment by cmarqu** [comment]
I'll offer the 7-bit ASCII version from my comment above:
```
⠙ 70/70  🎉 53  ⏰ 0  🤔 4  🙁 13
```
vs.
```
70/70    \o/ 53    -->| 0    :-? 4    :-( 13
```
with some coloring (and support for https://no-color.org/)

**Comment by Zac-HD** [comment]
I just substituted the words killed, timeout, suspicious, survived. It's not as pretty, but it is completely unambiguous.

**Comment by boxed** [comment]
Well it's unambiguous for sure, but it's also unintelligible for those not well versed in the nomenclature of mutation testing. That's why I have the emojis!
