### ISSUE TITLE
Bogus mutation: "* 1." -> "/ 1."

### ISSUE THREAD

**Issue by mattwelborn** [boxed/mutmut#150]
Example:

```
-        Z_available = molinit['elez'] * molinit['real'] * 1.
+        Z_available = molinit['elez'] * molinit['real'] / 1.
```

mutmut version 1.5.1

**Comment by boxed** [comment]
How is this a bogus mutation? without further information I would totally write that mutant manually if I did manual mutation tester.

**Comment by mattwelborn** [comment]
Thanks for the quick response!

The problem is that this mutation causes a false positive for every standard type. For numeric types -- I tested int, float, bool and corresponding numpy types -- `* 1.` and `/ 1.` give the same result (e.g. `42 * 1. == 42 / 1.`). For other types -- I tested list, set, str, dict, and None --- both `* 1.` and `/ 1.` cause a TypeError.

**Comment by boxed** [comment]
Ah. I see the problem. But the fault here is your code. It's an overly fancy way of writing float(...) which would have been much clearer and will pass mutation testing.

**Comment by mattwelborn** [comment]
Fair point. I'll close the issue and re-open if I can think of legitimate uses of `*1.`.

**Comment by boxed** [comment]
Cool! Always happy to hear people are using mutmut. Hope it goes well and I'd love to hear any more feedback you might have.
