### ISSUE TITLE
Feature request: Command to show every mutation for a file

### ISSUE THREAD

**Issue by EmilStenstrom** [boxed/mutmut#151]
Hi! I found myself wanting a way to run multiple show commands after each other. Just to see if there was one of them that was a "real" bug (most of the ones it found was changes to default values for class variables, that gets overwritten with another value afterwards anyways). 

Anyways, suggested syntax:

```
mutmut show path/to/file.py
```

Output would be the same as if you had run `mutmut show <id>; mutmut show <id2>; ...` for all id's for that file, BUT with the ID for each run prefixed with that run, so you could easily find that run later.

**Comment by boxed** [comment]
Seems reasonable and should be straight forward to implement.
