### ISSUE TITLE
Feature request: Way to ignore certain mutations

### ISSUE THREAD

**Issue by EmilStenstrom** [boxed/mutmut#152]
When running mutations on my [conllu](https://github.com/EmilStenstrom/conllu/) library, the majority of mutation errors are because I've decided not the test Exception message strings. Is there a way for me to set some kind of pattern that mutmut ignores? I found the `# pragma: no mutation`, but having that on all my `raise Exception("...")` feels dirty.

Any ideas?

**Comment by boxed** [comment]
Yea, this comes up frequently. The discussion is at https://github.com/boxed/mutmut/issues/47 

I haven't committed to a solution because I haven't heard enough real world use cases to know if the solution we settle for is going to cover the use cases.

**Comment by EmilStenstrom** [comment]
Thanks, will close this one in favour of previous discussions.
