### ISSUE TITLE
Shouldn't __str__ and __repr__ be excluded ?

### ISSUE THREAD

**Issue by roxanebellot** [boxed/mutmut#155]
I mean, they are not part of the *logic*, so mutating them would not be significant

**Comment by boxed** [comment]
Repr probably but str can absolutely be part of the logic of a program.

**Comment by l0b0** [comment]
I'd argue that if you actually *override* them you should test them. They both have rather specific semantics, and you work around those at your peril.

**Comment by roxanebellot** [comment]
Yay I agree it was not that good an idea. Maybe we can close this ?
