### ISSUE TITLE
What are suspicious mutants?

### ISSUE THREAD

**Issue by MartinThoma** [boxed/mutmut#159]
I can't find any explanation in the docs.

**Comment by boxed** [comment]
Mutants hwo seem to increase the test time significantly but not trigger the timeout threshold. 

It's really a crappy bucket due to the significant variations in timing that are normal but not having it is worse :(

**Comment by MartinThoma** [comment]
Cool, thank you :-) 

I really like the idea of mutation testing and mutmut seems to be the best option for python right now (I tried cosmic ray and mut.py as well). Maybe I'll make some PRs and try to contribute :-)

**Comment by boxed** [comment]
Yea, I also tried mutpy and cosmic ray.. that's why I wrote mutmut :P To be fair cosmic ray has really improved since I tried it first (I couldn't even get it to install back then!).
