### ISSUE TITLE
Automatic formatting

### ISSUE THREAD

**Issue by MartinThoma** [boxed/mutmut#160]
I have seen that code formatting is a potential (minor) issue in mutmut:

* [HTML report PR](https://travis-ci.org/boxed/mutmut/jobs/581979546): Fails
* [WIP different workers](https://github.com/boxed/mutmut/pull/145)
* [Flake8 PR](https://github.com/boxed/mutmut/pull/79)

I suggest the following:

* Use [black](https://github.com/psf/black) formatting: Instead of only complaining about formatting issues, black can automatically fix them. In my first project I was sceptical about it. I don't like all of the formatting it does. But it completely eliminates discussions about code formatting, as it doesn't allow customization. Besides `H301, H306, H404, H405, W503, E501, E203`, it is compatible with Flake8.
* Use [isort](https://pypi.org/project/isort/)
* Use [pre-commit](https://pre-commit.com/): ([example](https://github.com/MartinThoma/edapy/blob/master/.pre-commit-config.yaml)) - just to make sure that you really don't have to worry about it anymore.

What do you think?

**Comment by boxed** [comment]
None of the options actually help! Pre-commit hooks rely on the _client_ so only works if everyone didn't forget to install them. 

We are debating black at work but really it's not awesome. Elm-format is better in some crucial ways like it let's you choose between horizontal and vertical lists/argument lists/etc.  Black also thinks line length is a good measument which is a bit silly. Just counting commas would be better. 

If I get some time over I might check it out on mutmut though.  Maybe it works nicely in practice.

**Comment by MartinThoma** [comment]
I've never heard about elm format. Is it this: https://github.com/avh4/elm-format ?

> Pre-commit hooks rely on the client so only works if everyone didn't forget to install them.

Yes, of course. But black also has a pytest plugin: https://pypi.org/project/pytest-black/

So the developers can install the pre-commit hooks to get rid of formatting questions and the CI/CD pipeline can enforce it.

> We are debating black at work but really it's not awesome.

I also think the formatting is sub-optimal in some cases. But we introduced it at work and suddenly the reviews are less about style. That is a pretty big advantage :-) 

> Elm-format is better in some crucial ways like it let's you choose between horizontal and vertical lists/argument lists/etc.

That is exactly one advantage of black! It does NOT let you choose; it enforces one style and does not leave (much) room for debate :-) (there are things to configure, but only very few ... I think line length is one)
