### ISSUE TITLE
Better Results Handling

### ISSUE THREAD

**Issue by ryanfreckleton** [boxed/mutmut#161]
I've been using mutmut a bit, and I think it would be very useful to have some amount of management commands for handling mutations. The commands I'm thinking of are:

`mutmut pop <id>` which would apply a mutant and remove it from the results database.

`mutmut remove <id>` which would remove a mutant from the results database.

It might also be helpful to have a `mutmut audit` which would allow you to go through mutations one by one and drop/keep them.  I think this would be very useful with managing false-positives.

**Comment by boxed** [comment]
Interesting suggestions. This implies a way of working that is very different from how I work!

I do support `mutmut run <id>`. I find that often when I think I've killed a mutation I haven't actually so I think I would abuse "pop". 

As for removing false positives, I would love as many examples as you can find in the issue dealing with whitelisting. I would prefer if we can not produce false positives or have a whitelisting system that can handle them when they happen.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
