### ISSUE TITLE
Run baseline for every mutmut run

### ISSUE THREAD

**Issue by LizardWizzard** [boxed/mutmut#163]
Hello! Thank you for your project!

I accidently find out that if you run `mutmut run` and then broke your tests and then run `mutmut run` again, you will get: all mutants caught (because tests are broken). So the workaround is to remove mutmut cache and rerun again, but I think tool can be smarter in that case :) What do you think about that?

**Comment by boxed** [comment]
Yea I've been bitten by that many times myself. I just haven't gotten around to it.

**Comment by boxed** [comment]
Fixed in c8b25e18011bf85330935731af8639efa7fef152

I'm releasing a 1.8.1 bugfix release with this, since it's a pretty common pitfall.
