### ISSUE TITLE
Better whitelisting

### ISSUE THREAD

**Issue by joshz123** [boxed/mutmut#167]
I am using whitelisting with mutmut and to the best of my knowledge you can only whitelist with `#pragma: no mutate` It would be nice if there was some decorator or blockquote equivalent for whitelisting more than one line at a time. In my case, I had a very long hardcoded list of strings and had many failed mutations due to the strings being mutated even though the content of the string was irrelevant in this context.

**Comment by boxed** [comment]
This is a duplicate of https://github.com/boxed/mutmut/issues/47 where we have the discussion.

**Comment by boxed** [comment]
I have copied what you wrote in that PR. I have also asked a follow up question there.
