### ISSUE TITLE
Mutmut tests on windows is broken

### ISSUE THREAD

**Issue by boxed** [boxed/mutmut#168]
Hey @nklapste maybe you can take a look at this? I don't have a windows machine so I have to push to travis to try to figure this out and it's no fun at all.

On a brighter note, the new mutmut is suuuuuuper cool if you use it with hammett! You should try it out!

**Comment by DanJBower** [comment]
@boxed Mutmut seems to work for me if not setting `runner` in `setup.cfg` but when setting runner to `runner=python -m hammett -x -q src/tests` then none of the mutants seem to get killed even if they should be. Am I setting the runner wrong?

Using Python 3.7

**Comment by boxed** [comment]
You can run mutmut with the `-s` flag to see all the output. Maybe the hammett run ends up with zero tests?

**Comment by DanJBower** [comment]
I just tried the `-v` to see the verbose output. It definitely detects the tests, but it's almost like it is caching the first mutant or something

I tried running it on two files, separately and together

1st file - it says it kills all the mutants (I was expecting this)
2nd file - it says it killed none (but I was expecting it to kill half)
Both files at same time - it says it killed no mutants, even the ones against the first file which were working when run on its own

**Comment by DanJBower** [comment]
@boxed By any chance were you able to reproduce the issue?

**Comment by boxed** [comment]
Honestly I just don't have the time/energy to look at this. I will gladly accept a PR if you figure it out though.

**Comment by DanJBower** [comment]
No worries

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
