### ISSUE TITLE
Should support pyproject.toml as well as setup.cfg

### ISSUE THREAD

**Issue by dmyersturnbull** [boxed/mutmut#169]
My new projects don't have a setup.cfg, only a pyproject.toml and tox.ini.
Could mutmut be modified to read config options from either file?

**Comment by boxed** [comment]
Hmm.. Yea I guess pyproject.toml would be nice to support. A bit annoying if you have both files though...

**Comment by boxed** [comment]
I welcome PRs btw. I am pretty quick with merges, and the code base is not super big so should be ok-ish to get into.

**Comment by dmyersturnbull** [comment]
@boxed Sure, I'll give it a shot!
Looking through the code, where's `mutmut_config` supposed to be coming from?

**Comment by boxed** [comment]
I guess you'd only need to look at `config_from_setup_cfg` which is in `__main__.py`.

**Comment by MRocholl** [comment]
Is there any fork or PR associated with this? Otherwise Id submit one next week.

**Comment by boxed** [comment]
There isn't. A PR would be nice!

**Comment by laike9m** [comment]
Looking forward to pyproject.toml being supported

**Comment by MRocholl** [comment]
How do we want to treat redudant configuration in setup.cfg and pyproject.toml? Should any by default take precedence?
Open to suggestions.

**Comment by boxed** [comment]
I would suggest a hard error. Projects will have to pick one.

**Comment by izabelakowal** [comment]
Hi @MRocholl how's it going with the PR? Are u still working on that?

**Comment by jamesmyatt** [comment]
For multiple config files, tools like isort define an order of precedence and just use the first match: https://pycqa.github.io/isort/docs/configuration/config_files.html

**Comment by sed-i** [comment]
[Mypy](https://mypy.readthedocs.io/en/stable/config_file.html#the-mypy-configuration-file) too has an order of precedence ("fallback list") so it takes the first config it finds:

> Mypy supports reading configuration settings from a file.  By default it uses the file `mypy.ini` with a fallback to `.mypy.ini`, then `pyproject.toml`, then `setup.cfg` in the current directory, then `$XDG_CONFIG_HOME/mypy/config`, then `~/.config/mypy/config`, and finally `.mypy.ini` in the user home directory if none of them are found; the `--config-file` command-line flag can be used to read a different file instead
