### ISSUE TITLE
Add support for unittest-based Django tests

### ISSUE THREAD

**Issue by federicobond** [boxed/mutmut#17]
I'm attempting to run `mutmut` inside a Django project. There are certain assumptions in the codebase that I need to change in order to achieve that.

I will use this place to report my progress and welcome any ideas.

**Comment by boxed** [comment]
Django but not pytest?

**Comment by boxed** [comment]
I assume you already found some issues? Could you tell me what they are?

**Comment by federicobond** [comment]
* There isn't a single test directory in this project. Test directories are represented by the following glob pattern: `apps/**/tests/*.py`
 * Django test runner does not take any paths by default, should be able to execute `python manage.py test` without additional arguments.

**Comment by boxed** [comment]
I just noticed that mutmut inserts the tests directory as an argument to the runner command. You said so above but it didn't register with me because it's so obviously wrong! I'm gonna remove that.

**Comment by boxed** [comment]
I've pushed some changes that I think might fix the issues you've outlined above. Please give it a shot!

**Comment by federicobond** [comment]
The baseline test run executes fine, but then I reach this, which I don't know exactly how to debug:
```
Running tests without mutations... Done
--- starting mutation ---
Unchanged file core/celery_app.py
(cached existing) FAILED: mutmut core/celery_app.py --apply --mutation "        os.path.dirname(__file__), \"..\", \".env\"))⤑2"                             
(cached existing) FAILED: mutmut core/celery_app.py --apply --mutation "app = Celery('core')⤑1"
(cached existing) FAILED: mutmut core/celery_app.py --apply --mutation "app.config_from_object(\"django.conf:settings\", namespace='CELERY')⤑0"              
Unchanged file core/__init__.py
1 out of 583  (core/urls.py     url(r'^logout/?$', participants_views.logout, n                                                                              
FAILED: mutmut core/urls.py --apply --mutation "    url(r'^logout/?$', participants_views.logout, name='logout'),⤑0" 
...
```

**Comment by boxed** [comment]
I made a mistake before that I've now fixed. You should be seeing lots of mutants on the test files which was incorrect. Hopefully this is fixed now, I'd be very happy if you could confirm it. Better to make a clean run by deleting .mutmut-cache/ too.

If this does indeed fix that.. can I close this issue as solved?

**Comment by boxed** [comment]
While we're talking, is there any change you'd like to see in the documentation to clarify how to use mutmut?

**Comment by federicobond** [comment]
I think there are a couple of changes to the output that would make the process more transparent, like showing a simple diff of what is being changed with each mutation.

With `eth-mutants`, I experimented with the idea of assigning a unique hash (like a git commit) to each mutation, so if you see in the output:
````
 -> Applying mutation dc0868d
.... diff ....
````
You can later reference it like this to show a diff or apply it:
```
mutmut --diff dc0868d
mutmut --apply dc0868d
```

A mutation is defined completely by filename, start / end indexes and replacement text, so you can use them to compute a deterministic hash for each mutation.

**Comment by boxed** [comment]
If you're trying to actually kill the mutants then showing the diff is only going to be useful in the few cases where you want to add a no mutate pragma, and you wouldn't know that ahead of time anyway. It feels like having a diff feature would just become bad pedagogy where people might start to use it for their work flow even though it would be much worse.

Showing a diff for each mutation in the output would make the output super unwieldy for no real use I think. See logic above.

I've thought about using hashes but I opted for KISS when remaking the indexes (the indexes used to be filename and number). Using start/end indexes (I assume line numbers) is a big mistake, I had something like that before but it was a pain to use because you had to work with mutants from the bottom of the file up because otherwise you risked changing the code so the indexes changed. With the current system I don't have that problem.

**Comment by boxed** [comment]
Oh, and what about my questions above? Primarily: can I close this issue as fixed?

**Comment by federicobond** [comment]
> Using start/end indexes (I assume line numbers) is a big mistake, I had something like that before but it was a pain to use because you had to work with mutants from the bottom of the file up because otherwise, you risked changing the code so the indexes changed.

Yes, a file changing, in this case, should invalidate the previous mutants. I will give more thought to this problem though.

> Oh, and what about my questions above? Primarily: can I close this issue as fixed?

I have a couple more things to iron out and I would like to send you a PR with documentation changes later this week. I suggest leaving this open until I do that, but feel free to close it if you want.
