### ISSUE TITLE
Add support for unittest

### ISSUE THREAD

**Issue by pickfire** [boxed/mutmut#176]
Looks like `pytest` was expected `No module named pytest`. But some of the projects that I worked on uses `unittest` from python itself, is it possible for mutmut to support that?

**Comment by boxed** [comment]
Well it does support it, but you have to specify the runner. So in setup.cfg you add:

```
[mutmut]
runner=<your command>
```

...but mutmut could probably be better at trying to support this out of the box. Do you have an example project I could look at and see what command you need?

**Comment by pickfire** [comment]
No, the code for the project isn't open sourced. Let me check if that's possible.

**Comment by boxed** [comment]
What is the command to run the tests?

**Comment by pickfire** [comment]
```
python -m unittest
```

**Comment by boxed** [comment]
Oh, heh, well that should be easy to support if pytest doesn't exist.

**Comment by pickfire** [comment]
> Oh, heh, well that should be easy to support if pytest doesn't exist.

Huh? How come? How does pytest makes it hard to support?

**Comment by boxed** [comment]
> pytest may be faster once you get the hang of it.

Faster to develop with yes. But it's a lot slower: https://github.com/boxed/test-benchmarks/

**Comment by boxed** [comment]
I just committed an experimental fix for this issue on master. Could you try it out?

**Comment by pickfire** [comment]
Nice, it works now. But looks like mutation testing is not suitable for the project.
```
⠸ Running...Traceback (most recent call last):
  File "/home/ivan/act/apu/attendix/venv/bin/mutmut", line 10, in <module>
    sys.exit(climain())
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/mutmut/__init__.py", line 858, in wrapper
    f(*args, **kwargs)
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/mutmut/__main__.py", line 136, in climain
    sys.exit(main(command, argument, argument2, paths_to_mutate, backup, runner,
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/mutmut/__main__.py", line 252, in main
    baseline_time_elapsed = time_test_suite(
  File "/home/ivan/act/apu/attendix/venv/lib/python3.8/site-packages/mutmut/__main__.py", line 389, in time_test_suite
    raise RuntimeError("Tests don't run cleanly without mutations. Test command was: {}\n\nOutput:\n\n{}".format(test_command, '\n'.join(output)))
RuntimeError: Tests don't run cleanly without mutations. Test command was: python -m unittest
```
Probably because it hits the database too often such that there is some error being thrown already.

**Comment by boxed** [comment]
Well yes, mutmut requires the test suite to be stable and runnable. If you don't have that yet then mutation testing isn't a good idea.

**Comment by pickfire** [comment]
No, the test suite is runnable but I don't understand what do you mean by stable.

**Comment by boxed** [comment]
The message from mutmut above means the tests failed when trying to run without mutations. This should always work. It's like a sanity check before starting mutation testing.

**Comment by pickfire** [comment]
Nice, it works.
```
- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests needs to be expanded.
🔇 Skipped.          Skipped.

1. Using cached time for baseline tests, to run baseline again delete the cache file

2. Checking mutants
⠇ 692/692  🎉 666  ⏰ 1  🤔 0  🙁 25  🔇 0
```

**Comment by boxed** [comment]
Awesome! And damn good numbers you've got for not having done mutation testing before. Pretty impressive.

**Comment by pickfire** [comment]
Nice, but I was surprised it was pointing to some local (constant) variables I forgot to prepend with `_`.

```python
--- attendix/app.py
+++ attendix/app.py
@@ -7,7 +7,7 @@
 import typing

 cas_url = 'https://cas.apiit.edu.my/cas'
-api_url = 'https://api.apiit.edu.my/attendix'
+api_url = 'XXhttps://api.apiit.edu.my/attendixXX'

 logger = logging.getLogger()
 logger.setLevel(logging.INFO)

```

I just add `_` and the numbers reduced by 4 for survived. Haha.

Interesting project, quite nice to be able to do this without tweaking any code compared to the fuzzing tools I used in rust. I wish it is as easy there, interesting to see this tweaking the code but in rust for fuzzy/property-based testing people are tweaking the input to the function.

**Comment by boxed** [comment]
If you don't want to test logging, the readme has an example of how you can do advanced whitelisting. 

Rust doesn't have a mutation tester? Well there's a nice project idea then!

**Comment by pickfire** [comment]
> Rust doesn't have a mutation tester? Well there's a nice project idea then!

Rust compiles too slow (~5 seconds for an intermediate project), I don't think that's a nice idea.

**Comment by boxed** [comment]
Checked and there are two actually. They use mutation schemas so they don't need to recompile. I've fiddled with an implementation for mutmut to do that too actually.
