### ISSUE TITLE
DOC: What do the argument mutations do?

### ISSUE THREAD

**Issue by MartinThoma** [boxed/mutmut#177]
I'm currently reading through the mutations and I don't understand what the argument mutation is doing. From the name I would have assument that it changes the position of the arguments, but from the function I cannot see this.

Could you please explain it? (If you want, I can then create a docstring and make a PR)

**Comment by boxed** [comment]
If it's a `dict(....)` (or a dict synonym) it mutates the arguments one by one from `dict(a=b)` to `dict(aXXX=b)`.

It's sort of similar to the mutation for dict literals in the form `{'a': b}`, but unfortunately a bit different heh.

**Comment by MartinThoma** [comment]
Thank you! Should I add this as a docstring to the test or would you prefer it to stay as is?

**Comment by boxed** [comment]
A docstring in the function seems ok. The name of the function describes the part of the AST bring modified and that's good, but as you point out it lacks information on what it is doing with it.

**Comment by MartinThoma** [comment]
That was quick! Thank you for your help :-)

**Comment by boxed** [comment]
No thank you :)

**Comment by boxed** [comment]
I saw your blog post but couldn't find an email so I'm writing it here :( 

Some typos and similar:

"How do you tests" - drop the s

"A typical mistake are slight confusions" - singular or plural? 

"There are a couple of tools like cosmic-ray, but Anders Hovmöller did a pretty amazing job by creating mutmut. As of August 2020, mutmut is the best library for Python to do mutation testing. There is also mutpy and cosmic-ray, but mutmut was built after Anders saw the possibility to improve "  - Seems a bit redundant to mention cosmic ray twice. 

"In other languages, you might want to try those" - these

"Number mutations" - mutmut adds one to the numbers.

**Comment by MartinThoma** [comment]
Thank you very much! I appreciate that you took the time and read the article :hugs: 

I fixed all of them, except for

> "Number mutations" - mutmut adds one to the numbers.

I didn't quite understand what you mean by that. Is it wrong what I wrote?

My email is `info@martin-thoma.de` - I'm not quite sure where to post it on medium (except for adding it to every single article)

**Comment by boxed** [comment]
Well, what you wrote on numbers doesn't really explain much. Saying it just adds one is easier to understand and explains more. 

Ah. Yes well you didn't have your email here on Github or your homepage either :)
