### ISSUE TITLE
mutmut_config.py where?

### ISSUE THREAD

**Issue by blueskyjunkie** [boxed/mutmut#180]
Where is `mutmut_config.py` supposed to be placed? I've put it in the root directory of my project and `mutmut` analyses it and tells me I have mutation errors on it and it's not entirely clear at present that it is having any effect on configuration. 

Am I really supposed to write tests for the configuration of the tool testing my tests?

The documentation for the advanced configuration https://github.com/boxed/mutmut#advanced-whitelisting-and-configuration doesn't have any information on where `mutmut_config.py` is supposed to go, just examples of what is supposed to go in it.

Am I supposed to add `mutmut_config.py` to an exclusion list somewhere, somehow?

**Comment by BrijeshKrishnan** [comment]
Evan i am facing same issue with `mutmut_config.py` i placed it at root to skip print statement 

```
def pre_mutation(context):
    if current_source_line.strip().startswith('print('):
        context.skip = True
```
i don't see any effect of this file. Still i get escaped mutants at print

**Comment by boxed** [comment]
@blueskyjunkie you mean it's mutating it? That's weird. I guess your source directory is also the root of the project then?

**Comment by blueskyjunkie** [comment]
Here's the mutation results for mutmut_config.py

```shell
$ mutmut showmuu
To apply a mutant on disk:
    mutmut apply <id>

To show a mutant:
    mutmut show <id>


Survived 🙁 (25)


---- <project dir>/mutmut_config.py (8) ----

120-127
```

But if I try to show a result on the file I get an exception:

```shell
mutmut show 127
Traceback (most recent call last):
  File "<project dir>//.venv/bin/mutmut", line 8, in <module>
    sys.exit(climain())
  File "<project dir>//.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "<project dir>//.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "<project dir>//.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<project dir>/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/<project dir>/.venv/lib/python3.8/site-packages/mutmut/__init__.py", line 846, in wrapper
    f(*args, **kwargs)
  File "<project dir>/.venv/lib/python3.8/site-packages/mutmut/__main__.py", line 134, in climain
    sys.exit(main(command, argument, argument2, paths_to_mutate, backup, runner,
  File "<project dir>/.venv/lib/python3.8/site-packages/mutmut/__main__.py", line 180, in main
    print(get_unified_diff(argument, dict_synonyms))
  File "<project dir>/.venv/lib/python3.8/site-packages/mutmut/cache.py", line 191, in get_unified_diff
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '<project dir>/mutmut_config.py'
```

And oddly the config file does exist where mutmut is saying it does not.

Altogether confusing so far.

Should I just purge the cache and start again?

**Comment by blueskyjunkie** [comment]
I cleared the cache and did a fresh run and it seems to be working now.

I had already done a `mutmut run` before I introduced mutmut_config.py. I might be useful to note in the documentation that the cache needs to be purged after creating mutmut_config.py - it's a pretty reasonable use case for someone to start working with mutmut, see the results and realise they need some rules in mutmut_config.py to reduce the noise a little.

**Comment by BrijeshKrishnan** [comment]
### Folder structure

`C:\Projects\PythonRepo\mutmut_test>tree /F
Folder PATH listing for volume OSDisk
Volume serial number is B8EC-CC04
C:.
│   mutmut_config.py
│
├───src
│       sample.py
│       __init__.py
│
└───test
        test_sample.py
        __init__.py`


### Execution result

`C:\Projects\PythonRepo\mutmut_test>mutmut run

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests needs to be expanded.

mutmut cache is out of date, clearing it...
1. Running tests without mutations
⠇ Running... Done

2. Checking mutants
⠙ 1/1  🎉 0  ⏰ 0  🤔 0  🙁 1

C:\Projects\PythonRepo\mutmut_test>mutmut show 1
--- src\sample.py
+++ src\sample.py
@@ -4,4 +4,4 @@
     """ TODO """
     def func(self):
         """ TODO """
-        print("this is a sample")
+        print("XXthis is a sampleXX")`


`C:\Projects\PythonRepo\mutmut_test>mutmut --version
mutmut version 2.1.0`

### Code
sample.py

`import os

class dummy():
    """ TODO """
    def func(self):
        """ TODO """
        print("this is a sample")`

test_sample.py

`import os
import sys
import unittest
from sample import dummy

class TestSample(unittest.TestCase):

    def test_fail(self):
        dummyobj = dummy()
        dummyobj.func()
        pass

    
if __name__ == '__main__':
    unittest.main()`

**Comment by boxed** [comment]
> I cleared the cache and did a fresh run and it seems to be working now.

Hm.. that's good at least.

> I had already done a mutmut run before I introduced mutmut_config.py. I might be useful to note in the documentation that the cache needs to be purged after creating mutmut_config.py - it's a pretty reasonable use case for someone to start working with mutmut, see the results and realise they need some rules in mutmut_config.py to reduce the noise a little.

Well you shouldn't need to. This is clearly a bug.

**Comment by golankai** [comment]
Hi I'm having trouble configuring my mutmut and thought maybe it's connected to the `./setup.cfg`. Looks like:

```
[mutmut]
paths_to_mutate=./app/scripts/functions.py
backup=False
runner=python -m unittest
tests_dir=./app/tests/new_tests/
```

The problem is that it grabs more tests that crash him, that I didn't specify for him (they are not relevant but can't be deleted).

the new ones are in `./app/tests/new_tests/new_tests.py`
the old problematic ones are in `./app/tests/old_tests/old_tests.py`

running on Win10.
thanks!

**Comment by blueskyjunkie** [comment]
@golankai create a new issue. your question has nothing to do with this thread.
