### ISSUE TITLE
mutmut doesn't work with Python 3.9 because of Pony

### ISSUE THREAD

**Issue by henrikh** [boxed/mutmut#190]
Issue on the Pony repo about Python 3.9 support: https://github.com/ponyorm/pony/pull/565

**Comment by boxed** [comment]
Well that's annoying! Thanks for letting me know.

**Comment by kozlovsky** [comment]
We added support of Python 3.9 to the PonyORM repo, today we'll release the PonyORM version with Python 3.9 support.

**Comment by boxed** [comment]
Great news!
