### ISSUE TITLE
--tests-dir and --paths-to-mutate have inconsistent string separation behavior

### ISSUE THREAD

**Issue by icncsx** [boxed/mutmut#201]
Can we include a help message for --tests-dir and --paths-to-mutate and highlight the fact that one is colon separated and the other is comma separated?

Happy to make a pull request :)

**Comment by boxed** [comment]
I would propose that both should accept both comma and colon as separator. I will gladly take a PR!

**Comment by icncsx** [comment]
Will do so. Thanks!
