### ISSUE TITLE
mutmut "ignoring" test

### ISSUE THREAD

**Issue by SebRut** [boxed/mutmut#205]
Hi, I'm trying out mutmut on https://github.com/SebRut/pygrocy and mutmut  reports this mutant ([affected file](https://github.com/SebRut/pygrocy/blob/develop/pygrocy/data_models/meal_items.py)):

```
+++ pygrocy/data_models/meal_items.py
@@ -13,7 +13,7 @@
     def __init__(self, response: RecipeDetailsResponse):
         self._id = response.id
         self._name = response.name
-        self._description = response.description
+        self._description = None
         self._base_servings = response.base_servings
         self._desired_servings = response.desired_servings
         self._picture_file_name = response.picture_file_name
```

In my opinion this mutant should be killed with [this line](https://github.com/SebRut/pygrocy/blob/develop/test/test_meal_plan.py#L36) and indeed when running my tests manually using `pytest` and applying the mutant the test fails at the linked location.

**Comment by boxed** [comment]
Maybe the cache is doing this? You could try deleting `.mutmut_cache`

**Comment by SebRut** [comment]
I'm pretty sure I tried this before, but I'll give it another shot.

**Comment by SebRut** [comment]
Ok, I ran `mutmut run` again after removing `.mutmut_cache` but the mutant (and other mutants with similar issues that should be killed) still shows up.

**Comment by boxed** [comment]
That's strange. And if you do `mutmut apply <id>` you get the mutant you expect on disk and the tests fails?

**Comment by SebRut** [comment]
Yep, I recorded my repro steps here, maybe I'm missing something obvious: https://asciinema.org/a/YuWUnK3cmJtqvj1XLvVkRFMqW

**Comment by boxed** [comment]
Nice use of asciinema! I wouldn't have thought of that :P

Yea that looks pretty clear cut.

**Comment by willfrey** [comment]
I’m running into this issue as well.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
