### ISSUE TITLE
Possibly mistake on html table result

### ISSUE THREAD

**Issue by xwalls** [boxed/mutmut#215]
Hi! it is my first issue here, and it's a pleasure to help guys!
I'm getting the next html report, but i think there is a little mistake comparing the `mutmut run` result.

On the table, it is switching the total value of mutants with the killed ones

<h1>HTML RESULT</h1>
<h2>Mutation testing report</h2>Killed 25 out of 155 mutants<table>
    <thead>
        <tr>
            <th>File</th>
            <th>Total</th>
            <th>Killed</th>
            <th>% killed</th>
            <th>Survived</th>
    </thead>
    <tr>
        <td><a href="src/plot_burrows_density_map.py.html">src/plot_burrows_density_map.py</a></td>
        <td>25</td>
        <td>135</td>
        <td>18.52</td>
        <td>110</td>
    <tr>
        <td><a href="src/calculate_annual_percentages.py.html">src/calculate_annual_percentages.py</a></td>
        <td>0</td>
        <td>18</td>
        <td>0.00</td>
        <td>18</td>
    <tr>
        <td><a href="src/plot_burrows_density_map.py.html">src/plot_burrows_density_map.py</a></td>
        <td>0</td>
        <td>2</td>
        <td>0.00</td>
        <td>2</td>
</table>
</body>

</html>

<h1>MUTMUT RUN RESULT</h1>

1. Running tests without mutations
⠙ Running...Done

2. Checking mutants
⠦ 155/155  🎉 25  ⏰ 0  🤔 0  🙁 130  🔇 0

**Comment by boxed** [comment]
This looks like the same as #184

I've released 2.2.0 that includes this fix.
