### ISSUE TITLE
Add the possibility to disable emojis

### ISSUE THREAD

**Issue by exhuma** [boxed/mutmut#216]
I'm running the latest ArchLinux with the most recent version of NerdFonts (both updated just before posting this issue) and still don't see the emojis of mutmut which makes the output a bit hard to read.

I've come across 63e544367b while searching for a solution to the problem. But it seems this commit does not have hit the official distribution yet. I'm running mutmut 2.1.0 and the CLI-arg is not present.

**Comment by boxed** [comment]
I've released 2.2.0 that has this change in it.

**Comment by exhuma** [comment]
Wow. This was quick. Thanks a lot!
