### ISSUE TITLE
Fails to detect test failure when mutating default argument

### ISSUE THREAD

**Issue by l0b0** [boxed/mutmut#221]
How to reproduce in a repo with a convenient 100% test coverage:

1. `git clone git@github.com:linz/template-python-hello-world.git`
2. `cd template-python-hello-world`
3. `git checkout tests/introduce-mutation-testing`
4. `poetry install`
5. `. .venv/bin/activate`
6. Delete the last two tests in tests/test_salutation.py. This way, only the test which uses the default argument value is left:
   ```
   def test_hello_without_name() -> None:
       assert hello() == "Hello, World!"
   ```
7. `mutmut run`

Expected result: `mutmut run` should indicate a failure because of mutating the `name` argument default in src/salutation.py.

Actual behaviour: `mutmut run` says it killed one mutant, and exits successfully.

Additional details: It looks like the relevant mutation was not applied before running the test:

```
$ mutmut show 1
--- src/salutation.py
+++ src/salutation.py
@@ -1,3 +1,3 @@
-def hello(name: str = "World") -> str:
+def hello(name: str = "XXWorldXX") -> str:
     return f"Hello, {name}!"
 ```

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
