### ISSUE TITLE
``mutmut_config.init()`` not called

### ISSUE THREAD

**Issue by DudeNr33** [boxed/mutmut#224]
I have troubles in getting my ``mutmut_config.py`` to do what I want it to.

The content ist:
```python
def init():
    from mutmut import mutations_by_type
    del mutations_by_type["string"]
    print(mutations_by_type)
```

When I run ``mutmut run``, the ``init()`` is not called.

What I could analyse so far:
* all the imports (from ``mutmut``'s ``__init__.py`` and ``__main__.py``) are done twice when running ``mutmut``, once when starting the program and once after the "2. Checking mutants" message
* At the first import, ``mutmut_config`` cannot be imported and is None. That is why the ``init()`` is not called. Only after the second import it can be loaded, and things like ``pre_mutation(context)`` work as expected

My directory layout is:
```
(.venv) tracematrix [try-mutmut●●] % tree
.
├── CHANGELOG.md
├── LICENSE
├── README.md
├── mutmut_config.py
├── poetry.lock
├── pyproject.toml
├── src
│   └── tracematrix
│       ├── item.py
│       ├── matrix.py
│       └── reporters
│           ├── __init__.py
│           ├── base_reporter.py
│           ├── csv_reporter.py
│           ├── html_reporter.py
│           └── template.html
└── tests
```

**Comment by boxed** [comment]
That's a fun hack :P

Well.. I can't tell you why the import fails the first time. Have you tried just printing `sys.path` and seeing what it is?

**Comment by DudeNr33** [comment]
Indeed the ``sys.path`` changes. I added some good old ``print``s, here is the output:

```console
(.venv) tracematrix [try-mutmut●●] % mutmut run
__init__: starting
__init__: sys.path is  /Users/andreas/programming/oss_projects/tracematrix/.venv/bin
/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9
/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
/Users/andreas/programming/oss_projects/tracematrix/.venv/lib/python3.9/site-packages
/Users/andreas/programming/oss_projects/tracematrix/src
__init__: importing mutmut_config
__init__: None
__main__: starting
__main__: importing from __init__

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests need to be expanded.
🔇 Skipped.          Skipped.

1. Using cached time for baseline tests, to run baseline again delete the cache file
__main__: None

2. Checking mutants
⠼ 45/54  🎉 45  ⏰ 0  🤔 0  🙁 0  🔇 0__init__: starting
__init__: sys.path is  /Users/andreas/programming/oss_projects/tracematrix
/Users/andreas/programming/oss_projects/tracematrix/.venv/bin
/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9
/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
/Users/andreas/programming/oss_projects/tracematrix/.venv/lib/python3.9/site-packages
/Users/andreas/programming/oss_projects/tracematrix/src
__init__: importing mutmut_config
__init__: <module 'mutmut_config' from '/Users/andreas/programming/oss_projects/tracematrix/mutmut_config.py'>
__main__: starting
__main__: importing from __init__
⠹ 54/54  🎉 45  ⏰ 0  🤔 0  🙁 9  🔇 0
```

As you can see, the current working directory is missing the first time.

**Comment by boxed** [comment]
Hmm.. that seems strange to me. Does that mean if you do this:

```
> python
>>> import mutmut_config
```
it also fails?

**Comment by DudeNr33** [comment]
No, I had already tried this and it works. 
I could move ``mutmut_config.py`` into ``src`` as this folder is present in the path at both times (because I installed the package in editable mode), but I'd rather understand the problem. 
I also tried running ``mutmut`` through ``poetry`` as well as directly after activating the virtualenv created by ``poetry``.
Even if I create a completely fresh virtualenv (without using ``poetry``) the result is the same, so its probably not an issue caused by ``poetry``.

Could you verify that it works on your machine?

**Comment by boxed** [comment]
Well.. I don't have the src style layout. That's not really the common case for python code from what I know, so maybe that's the reason. Maybe the docs should just be changed...

**Comment by DudeNr33** [comment]
I think it was more common to use a non-src layout in the past, but there are a [few good arguments](https://hynek.me/articles/testing-packaging/) to use a src-style layout.
Even the [official PyPA tutorial](https://packaging.python.org/tutorials/packaging-projects/) now uses the src-style layout.

However I am not really sure if this really is the source of the problem. I will experiment a bit and check if it changes anything when using a non-src layout.

**Comment by DudeNr33** [comment]
Apparently when running the entry point ``mutmut`` [only the script directory](https://stackoverflow.com/a/6416470/4030694) is added to ``sys.path``, not the working directory. 
This behaviour was different until Python 3.4 according to the comments, so that's why this might have used to work earlier.

``__main__.py`` already adds the current working directory to ``sys.path`` on line 51, that's why the second import succeeds.
The solution is probably to just move the
```python
if os.getcwd() not in sys.path:
    sys.path.insert(0, os.getcwd())
```
up a few lines so that it is executed before the import from ``__init__.py``.

**Comment by DudeNr33** [comment]
I have a fix and some additional tests, will make a PR tomorrow for this!

**Comment by boxed** [comment]
Great!
