### ISSUE TITLE
Add option to take coverage contexts into account

### ISSUE THREAD

**Issue by DudeNr33** [boxed/mutmut#227]
``coverage.py`` is able to capture [dynamic contexts](https://coverage.readthedocs.io/en/coverage-5.5/contexts.html#dynamic-contexts), which means it can track which test exercised which parts of the code under test.

As ``mutmut`` is already able to read the coverage database, it could significantly improve the execution times if it would take this context data into account and only run the tests that actually cover the mutated line.

If no context was recorded or the context is not the name of a test function (e.g. a user-defined static context for example), ``mutmut`` should run the whole test suite as a fallback. 
This feature should probably also be optional.

**Comment by boxed** [comment]
Yea. This has been on my todo list since nedbat first mentioned he was working on this feature.

I believe the tricky part here is to tell the test framework which tests to execute. The beauty of the current mutmut approach is that it really doesn't care about what the runner is. This feature probably needs to know some details of the runner.

**Comment by DudeNr33** [comment]
The way I understand so far, ``mutmut`` would need to deal with two things that are out of its own control and may be highly dependent on the tools used:
1. as you already said, the runner command to use when executing tests
2. How to extract the test cases from the context information in the coverage database

I already noticed that different tools use different notations for the dynamic contexts. 
``coverage`` itself uses ``<module>.<test_function>``, but is only able to correctly track test functions defined at module level. If someone uses test classes, those tests will not show up as context information.
``pytest-cov`` is able to correctly also identify tests inside test classes, but uses a different notation:
``<path/to/file>::<TestClass>::<test_function>|run``.

I was thinking about approaching it in a similar way as with the current ``runner`` option.
``mutmut`` defines what information it needs from the coverage database and what it wants to pass to the runner.
The user then tells ``mutmut`` how to construct the call that is made to start the test runner.

Let's say ``mutmut`` only wants to extract the name of the test case itself (assuming all major test runners have a similar option to the ``-k`` option of ``pytest``), the user would define these two options:

```config
[mutmut]
use_context_info=True
context_regex=(?P<test_case>\w+)(\|run)*$
context_runner=pytest -x -k {test_case}
```

The first option is a regex that is used to extract the test case name from a context name in the coverage database. 
The next option is the runner command which is used to run the test case(s) covering the mutated line.

This way ``mutmut`` does not need to know more about the test frameworks. For the commonly used frameworks like ``pytest``, ``unittest`` and ``nosetest``, ``mutmut``'s documentation can give examples how to set up the config file, so the users don't have to figure it out themselves.
But if someone has a lesser known test runner or uses custom methods to capture context information, he is still able to use this feature.

To make all of this more robust, an additional option to run the whole test suite if the mutants survives after only running the subset of test cases could be added as well.

What do you think?

**Comment by boxed** [comment]
Hmm. Maybe we should do something even more flexible with the mutmut config python file we already have. 

This reminds me that we need to research testmon again for mutation testing. First time I tried it it was way too slow, but they've rewritten it so it's radically faster now.

**Comment by DudeNr33** [comment]
That sounds like a good idea.
What would be your approach? Have a single callback that gets the context (or list of contexts?) and directly returns the command which shall be used to run the tests? 

I had a quick look at ``pytest-testmon``. The way I see it, ``mutmut`` already supports it? So for ``pytest``, we'd already be set. At least if ``pytest-testmon`` is fast enough now (haven't tried it yet, and of course the question is if a custom approach in ``mutmut`` is actually faster).
On the other hand, this is only available for ``pytest`` users. Granted, this is the most common test framework, but as you said, ``mutmut`` aims to be test framework agnostic.

I think the solution with ``mutmut_config.py`` would work for all test frameworks and could be a fairly small change to the existing code, if you are open to a PR for this I would take a look.

**Comment by DudeNr33** [comment]
Another benefit from the ``mutmut_config.py`` approach is, that projects that have some direct relation between the production and test code layout could select the relevant tests even without coverage data.

**Comment by boxed** [comment]
> What would be your approach? Have a single callback that gets the context (or list of contexts?) and directly returns the command which shall be used to run the tests?

Single context, returns the command seems reasonable to me. You could maybe think of a scenario where you want the actually running execution to be overridable but that seems like a separate thing.

> The way I see it, mutmut already supports it? 

Yes. But is it practically useful? That's the question.

>  if you are open to a PR for this I would take a look.

I am.

> Another benefit from the mutmut_config.py approach is, that projects that have some direct relation between the production and test code layout could select the relevant tests even without coverage data.

That's a good point. We do this in iommi where `foo.py` has `foo__tests.py`, for this very reason. https://github.com/TriOptima/iommi/blob/master/mutmut_config.py
