### ISSUE TITLE
``mutmut show all <filename>`` and ``mutmut show <filename>`` equivalent?

### ISSUE THREAD

**Issue by DudeNr33** [boxed/mutmut#229]
During the last PR I was a bit confused what the second argument to ``mutmut show <argument> <argument2>`` should be.

The code is the following:
```python
def print_stuff(title, mutant_query):
    mutant_list = sorted(mutant_query, key=lambda x: x.line.sourcefile.filename)
    if mutant_list:
        print('')
        print("{} ({})".format(title, len(mutant_list)))
        for filename, mutants in groupby(mutant_list, key=lambda x: x.line.sourcefile.filename):
            if print_only_filename is not None and print_only_filename != filename:
                continue

            if only_this_file and filename != only_this_file:
                continue
```

At first I thought that the second argument means "print only the filenames that have surviving mutants".
But reading the commit message for the first ``if`` in the ``for`` loop, I guess that the intention was to display all mutant diffs for this specific file:
"Display all diffs for surviving mutants for a specific file with `mutmut show all path/to/file.py`"

However, this is also possible by just running ``mutmut show path/to/file.py``. 
Hence the two ``if`` blocks effectively do the same thing. 

The question is: how should we proceed? 
Just drop the second argument, or use it to actually just list the names of the affected files?

**Comment by boxed** [comment]
Oops.  Yea just drop the "all" syntax. Probably just me being confused. Better help text is the way to go.
