### ISSUE TITLE
``--cache-only`` option does not do anything?

### ISSUE THREAD

**Issue by DudeNr33** [boxed/mutmut#230]
``--cache-only`` can be passed as an option to the ``run`` command.
However, this option seems to have no effect. It is passed into the ``Config`` class, but never accessed again. 

From the discussion in PR #228:
> I think it's supposed to just update the cache, ie the database of where line numbers are and such. Mutmut can handle if you add a line in the beginning of the file and all line numbers move one step. That's why this command exists. It might be a bit subtle what it actually does :P

**Comment by boxed** [comment]
I say kill it.
