### ISSUE TITLE
Bug with --disable-mutation-types and --enable-mutation-types

### ISSUE THREAD

**Issue by brutalsavage** [boxed/mutmut#234]
Hi I have been testing out the new commands since they are quite useful. However I found some bugs related to them. 

Here is a testProgram for mutation purpose 

```
def testfunction(): 
    array['a'] = 123
```

I run this command after building v2.3 `mutmut run --enable-mutation-types=number --paths-to-mutate testFunction.py` 
followed by 
`mutmut show all`

and here is the output:

```
To apply a mutant on disk:
    mutmut apply <id>

To show a mutant:
    mutmut show <id>


Survived � (1)

---- testFunction.py (1) ----

# mutant 1
--- testFunction.py
+++ testFunction.py
@@ -1,3 +1,3 @@

 def testfunction():
-    array['a'] = 123
+    array['XXaXX'] = 123
```

This seems like a string mutation and not a number mutation, the correct number mutation after taking a brief look at the source code shoule be something like `array['a'] = 124`

You can get a similar "wrong" output when you run `--disable-mutation-types=string`

I am not very familar with the code base but I think this bug has something to do with overwriting mutations? see these lines https://github.com/boxed/mutmut/blob/cc7e7825a8a2ca0d5abb5f4748aa8c8ccea7f0f7/mutmut/__init__.py#L629-L643

**Comment by DudeNr33** [comment]
Thank you for reporting this! I can reproduce it. 
I'll have to look into this in more detail, but apparently ``context.config`` is ``None`` at some point when ``mutate_node(node, context)`` is called. In this case the check for mutation types to apply cannot be performed, because this information is stored in the ``config`` object.
Don't know yet why this happens though.

https://github.com/boxed/mutmut/blob/cc7e7825a8a2ca0d5abb5f4748aa8c8ccea7f0f7/mutmut/__init__.py#L601-L604

**Comment by boxed** [comment]
I'm not sure I agree with the premise. The mutant you showed is still there and not killed. It's just that you haven't tested it with mutmut. One could argue that `mutmut show --enable-mutation-types=number` would only show number mutation types though. That makes sense to me. And that's sort of what you'd get if you put that setting in the config file instead of the command line.

**Comment by DudeNr33** [comment]
It can be discussed what the desired behavior should be, but that the disabled Mutation types show up as surviving mutants in ``mutmut show all`` is definitely not what I was aiming for, and have simply missed it. 
We could maybe mark them as skipped instead? 
This way the User can still see how many additional mutations ``mutmut`` could generate when all mutation types are enabled. 
I am open for suggestions, but I definitely don't want to leave it the way it is right now.

**Comment by boxed** [comment]
Yea, skipped seems reasonable. 

Have you tried putting this configuration option in the config file? It might do the right thing already.

In general the command line arguments as an option are a source of problems. It's much better if the config file is used always... maybe that was a design flaw from the beginning by me.

**Comment by brutalsavage** [comment]
I took a look at it some more and I think the problem is what @DudeNr33 suggested before, `context.config` is `None` during `mutmut show`. The reason is that for printing `mutmut show` uses the function `_get_unified_diff` and in there a `context` object is initialized but without specifying the `config` which means `context.config` is `None` and cause `mutate(context)` to not behave like it did when you call `mutmut run --enable.....` 

I am using this project as a way of generating mutants so I am not really using the command line but using it as a library and I've tested it by giving the `_get_unified_diff` the same `config` as before it works fine. 

Again I am not very familar with how caching works for this project, but I think `config` should be cached and then reused for future `show` commands, I think that will solve this problem. 

https://github.com/boxed/mutmut/blob/8b7c763a6e2c3354cc8f40c68648dd4415197471/mutmut/cache.py#L206-L219

**Comment by DudeNr33** [comment]
Yes, that would solve the problem. I want to take a closer look at the caching mechanism first though.
I had expected that the cache already stores the actual mutation, but it seems like ``mutmut show <id>`` computes the possible mutations again. 
This was not an issue so far as the types of mutations to apply were always the same, but this premise no longer holds after I introduced this new option.

**Comment by DudeNr33** [comment]
``mutmut`` computes an array of possible mutations for each source code line. 
The cache stores the ``line`` and the ``index`` (that is: the index in the array of possible mutations):

```python
class Mutant(db.Entity):
    line = Required(Line)
    index = Required(int)
    tested_against_hash = Optional(str, autostrip=False)
    status = Required(str, autostrip=False)  # really an enum of mutant_statuses
```

In my original implementation for ``--enable-mutation-types`` I returned too early from the ``mutate_node`` method and broke this indexing mechanism. 
With the linked PR ``mutmut`` now correctly identifies all possible mutations again, but simply does not perform a mutation if it does not belong to the desired mutation types.
