### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by iirekm** [boxed/mutmut#236]
Currently I add the following to `setup.cfg`:
```
[mutmut]
runner=sh -c 'pytest --exitfirst --inc "$@" || [ $? = 5 ]' -
```

However it would be good to have enabled these by default. Other optimizations are also possible e.g.:
- not running new Python process for every run - some libraries e.g. Tensorflow load quite slowly
- parallel execution

**Comment by DudeNr33** [comment]
Hm, I would be glad if at least there would be a fallback mechanism for sequential execution to still support Windows and macOS.

@iirekm why is the ``"$@" || [ $? = 5 ]' -`` necessary? 
If I understand correctly you use this to say "run the tests but if you don't find any that's also OK" (as exit code 5 is "no tests collected")?

**Comment by iirekm** [comment]
Having 3 separate impls (one for lx, one for win, one for Mac) is even
bigger risk of bugs 😔
Maybe the thing you want to do is done by somebody in form of a library,
ported to all 3 systems?

pt., 8 paź 2021, 13:32 użytkownik Anders Hovmöller ***@***.***>
napisał:

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
