### ISSUE TITLE
PyTest failing after succesful mutmut run

### ISSUE THREAD

**Issue by tea-418** [boxed/mutmut#237]
I got the following issue with running mutmut tests, which I can reproduce with the following steps:

1. I have unit tests, I want to test using mutmut. So I run `mutmut run`
2. The mutmut tests pass!
3. I run pytest to run the unit tests without mutations.
4. The tests fail, which should not happen (they worked before running mutmut).
5. If I delete the `__pycache__` folder and re-run pytest, pytest passes again.

My setup is Windows with python 3.9, mutmut 2.2.0 running in poetry environment.

My suspecion is, that mutmut creates "wrong" files/does not clear the mutated versions in __pycache__, and therby confuses pytest.

I searched far and wide but did not find anyone with the same issue.

Thanks for any help!

**Comment by drjasonharrison** [comment]
Adding to this for posterity. /s

I ran mutmut using the terminal in vscode and had the same problem with manual runs of pytest failing when using the terminal in vscode.

pre-commit hooks did not have a problem.

Deleted the __pycache__ directories, etc and everything worked again.

In the vscode terminal, the environment variables include `TERM_PROGRAM=vscode`
