### ISSUE TITLE
Releasing version 2.3.0

### ISSUE THREAD

**Issue by Jhnbrn90** [boxed/mutmut#243]
Hi @boxed 

First of all, thanks for all your work on this project! It is super useful and has certainly proven its worth.

Now, I'd like to use some of the newly added features available in the `master` branch (like the documented `--disable-mutation-types` option) but unfortunately can't rely on outside connections to GitHub since all packages are retrieved from an internally hosted Pypi server within the company.

Therefore, I'd like to ask you if it would be possible to tag release version `2.3.0` any time soon, so we can port that version to our internal repository.

Thanks in advance!

Best regards, 

John Braun

**Comment by boxed** [comment]
2.4.0 is released.

**Comment by Jhnbrn90** [comment]
Thanks Anders!
