### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by islomar** [boxed/mutmut#244]
Hi!

Not sure what would be the best way to propose a contribution, so I will just try to write it here.
I would like to propose to **dockerize mutmut**, so that anyone could use it without any dependency to `pip` or having to install anything locally (besides Docker, of course).

I could work on it and create a MR with it (and including pushing the image to Docker Hub), but before investing time I would like to be sure that the idea is accepted.

What do you think? :smile:   /cc @boxed @DudeNr33 @felixdivo

**Comment by felixdivo** [comment]
[I'm not really an active part of the project.] But containerizing sounds nice, even though installing `mutmut` using `pip` is really easy (no binaries are compiled and no weird dependencies)! However, I don't quite understand how this would work, given mutmut runs your code with your dependencies. Wouldn't you have to add them to the container too?

**Comment by DudeNr33** [comment]
Thank you for offering your help!

As I don't normally use containerised versions of tools and instead install them directly in my work environment, could you please elaborate on the advantages of running ``mutmut`` inside a container instead of your local development environment?

**Comment by boxed** [comment]
I don't see the point honestly. If you want mutmut isolated, there's pipx for that. If you can't install packages, you probably can't use mutmut in the first place. I don't see where there's an advantage in this where downloading a docker image of a hundred mb or whatever makes sense.

**Comment by islomar** [comment]
I know more a nd more people who don't use any kind of tool unless it is dockerized. It would be a way to remove friction for its use.
On the other hand, a typical use case is the integration in a CI/CD pipeline; you just run the image and don't need to install anything on top (but maybe I am missing something here).

Since I don't see enough interest (no problem), I will do it for myself then and if I can see something useful, I will come back and share it in a more specific way :smile: 
I will close the issue.
