### ISSUE TITLE
HTML Report numbers are misplaced

### ISSUE THREAD

**Issue by MirceaZisu** [boxed/mutmut#245]
I have recently started testing the application of `mutmut` on my non-public project, and I wanted to mention that the numbers present in the html report are misplaced. 

As can be seen in the screenshot below, the total number of mutants is 0, while 15 mutants got killed, and 15 survived. The arrangement that makes sense in that case is 15 mutants in total, 0 got killed and 15 survived.

![image](https://user-images.githubusercontent.com/62066453/156148974-0aee7ca7-5f4c-42ae-bc80-4575e47d7131.png)

**Comment by boxed** [comment]
This is not relevant anymore, as html reports are not implemented in current mutmut.
