### ISSUE TITLE
Moving mutmut to a different folder than working directory

### ISSUE THREAD

**Issue by MirceaZisu** [boxed/mutmut#246]
As title says, I wanted to be a bit more organized, and put everything related to `mutmut` in `/tests/mutation`. I attempted to run `mutmut html`, and it says it can not find one of the project files, even though `mutmut run` is running with the appropriate number of mutants being checked.

I have gotten setup.cfg and mutmut_config.py setup, and mutmut was running, although the tests were incredibly fast. After the mutations had completed, I brought the setup files in the working directory, and ran `mutmut html` again. This time it worked, but none of the files of the files in the html report. 

Any clue how I could move the mutmut configs into a separate folder, and get it running (especially with the 100-mutant bug), until it runs out of mutants to check?

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
