### ISSUE TITLE
setup.cfg for specifying the tests to use won't kick-in

### ISSUE THREAD

**Issue by golankai** [boxed/mutmut#249]
Hi I'm having trouble configuring my mutmut to run only a specific set of tests. My './setup.cfg' looks like:

```
[mutmut]
paths_to_mutate=./app/scripts/functions.py
backup=False
runner=python -m unittest -v
tests_dir=./app/tests/new_tests/
```

The problem is that it grabs more tests than it is meant to, which crushes him (they are not relevant but can't be deleted).

the new ones (which I want to use) are in `./app/tests/new_tests/new_tests.py`
the old problematic ones are in `./app/tests/old_tests/old_tests.py`

running on Win10.
thanks!

**Comment by boxed** [comment]
You need to specify what tests to run in the `runner` command. The `tests_dir` setting is just for mutmut to be able to figure out if the tests have changed since last run.

**Comment by golankai** [comment]
thanks!!! works :)))

**Comment by pogopaule** [comment]
@boxed It took me some time to find this issue. I somehow expected that setting `--paths-to-mutate` and `--tests-dir` would be enough to narrow down the code and tests that mutmut looks at. Do you think adding that to the docs is the way to go? I'd be happy to make a PR.

**Comment by boxed** [comment]
A PR for better docs is always appreciated.
