### ISSUE TITLE
Number mutation doesn't handle decimal numbers between 0 and 1

### ISSUE THREAD

**Issue by rtbound** [boxed/mutmut#25]
Hi,

Attempting to mutate the following line fails with an assertion error:

`self.something = 0.1`

File "[...]/venv/lib/python3.5/site-packages/mutmut/__init__.py", line 44, in number_mutation

assert base == 10
AssertionError

This seems to be related to the following lines of mutmut/__init__.py (lines 37-45):

 ```
...
elif value.startswith('0') and len(value) > 1:  # pragma: no cover (python 2 specific)
        base = 8
        value = value[1:]
    else:
        base = 10

    if '.' in value:
        assert base == 10
        parsed = float(value)
...
```

`self.something = 10.1` works
`self.something = .1` works
but
`self.something = 0.1` does not work

I've worked around this currently by replacing all numbers between 0 and 1 without a '0' before the decimal point, however this is not a long term solution or suitable for a large project.

I am using Version: 0.0.22

Thanks

**Comment by boxed** [comment]
https://github.com/boxed/mutmut/pull/24

The fix for this was merged two days ago :P I haven't had time to make a release but if you'd like to try out the master version first to validate the fix I would be very greatful!

**Comment by boxed** [comment]
I've rolled a new release that includes this fix. Thanks for trying out mutmut and especially for reporting your problems! If you have any more please let me know and I'll try to get you up and running.

**Comment by rtbound** [comment]
Thanks, the fix works
