### ISSUE TITLE
2.4.2 release?

### ISSUE THREAD

**Issue by srazzell** [boxed/mutmut#265]
I would like to use the changes that are on master, but I'm currently having to install by cloning the repo. Would it be possible to do a new release of mutmut to make it easier to get the latest changes for those of us using an internally hosted mirror of pypi? Thanks in advance.

**Comment by boxed** [comment]
Released a version now. Thanks again. 

In accordance with my policy of repeat contributors I have invited you to the project.

**Comment by srazzell** [comment]
Thank you!
