### ISSUE TITLE
Mutmut HTML not working with Python 3.11

### ISSUE THREAD

**Issue by St4rG00se** [boxed/mutmut#266]
Hello,

Because of pony dependency, `mutmut html` not working when using Python 3.11.0 

Indeed, this command throws: `pony.orm.decompiling.DecompileError: Unsupported operation: RETURN_GENERATOR`

It seems mutmut is not the only concerned project [pony/issue/668](https://github.com/ponyorm/pony/issues/668)

**Comment by nickdrozd** [comment]
A crummy workaround is to use 3.11 to run the tests, but an earlier version (say, 3.8) to view the output.

**Comment by boxed** [comment]
Pony has now released a new version that works with python 3.11.
