### ISSUE TITLE
mutmut exit codes incompatible with GitHub Actions

### ISSUE THREAD

**Issue by maxkahan** [boxed/mutmut#267]
Hi, I'm trying to set up a mutation testing workflow in GitHub Actions. GitHub Actions [only accepts an exit code of 0 as a succesfully completed step](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions), showing a build failure for any other exit code that's returned.

This means that unless every single mutant is caught, the workflow will fail, as otherwise a status of 2, 4, or 8 is returned. Currently I'm getting around this with some bash: 

```bash
mutmut run --no-progress || \
if [ $? -eq 1 ]; then exit 1; fi # to catch exception return code 1
```

Which feels pretty hacky 😞 

Would you consider adding an option/flag that, when set, makes mutmut return either a 0 for any successfully completed run, or 1 for a run where an exception is raised?

Thanks in advance!

**Comment by boxed** [comment]
I guess that could go into the CI flag. Yea, I'm open for a PR for this.

**Comment by maxkahan** [comment]
Sure, I've been playing with this, I can submit a PR 🙂

**Comment by maxkahan** [comment]
Have made PR #268 that adds a `--CI` flag that makes this behaviour happen.
