### ISSUE TITLE
Option to skip initial test run

### ISSUE THREAD

**Issue by boxed** [boxed/mutmut#27]
This is useful for testing scenarios and to speed up re-running stuff if you're pretty sure this step will succeed. The downside is of course that mutmut can't detect excessively long test runs.

**Comment by boxed** [comment]
Maybe we could store the baseline time duration in the cache and reuse that if the tests hash is unchanged?

**Comment by blueyed** [comment]
Yeah, using/storing the baseline in the cache makes sense.
(but I have not checked what the cache (key) is based upon really)

**Comment by boxed** [comment]
It's an SQLite db now so it probably would be a table with a single row.

**Comment by boxed** [comment]
Come to think of it, just assuming the test suite doesn't radically change execution time even if the tests hash has changed is probably fine. The timeout is set to 10x the baseline so should be fine. If it isn't you can just delete the .mutmut-cache file and continue.
