### ISSUE TITLE
I have no idea why the “mutmut run” doesn't work

### ISSUE THREAD

**Issue by MaxwelsDonc** [boxed/mutmut#274]
### Environment
the environment is python3.6 on windows 10. (I first started with python3.9, but mutmut didn't work, so I changed to 3.6. But mutmut still doesn't work.)

### File Structure

>mutant
>>mortgage_rate.py(python)
tests(dir)
>>>test_mortgage_rate.py(python)

#### mortgage_rate.py
```
def mortgage_rate_cal(house_value):
      prime_rate = 1
      if house_value >= 205000:
          mortgage_rate = prime_rate + 1.75
      else:
          mortgage_rate = prime_rate + 1.27
      return mortgage_rate * house_value
```
#### test_mortgage_rate.py
```from mortgage_rate import mortgage_rate_cal
import unittest
class TestMortgageRate(unittest.TestCase):

    def test1(self):
        self.assertEqual(mortgage_rate_cal(10000), 22700)

    def test2(self):
        self.assertEqual(mortgage_rate_cal(500000), 1375000)
if __name__ == '__main__':
    unittest.main()
```
### Problem
when i type `mutmut run` or `mutmut run --paths-to-mutate .\mortgage_rate.py` it does not generate mutants but output `OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'tests\\:test'`
I dot know how to fix it.

**Comment by boxed** [comment]
I don't read Chinese. You'll have to translate that, or better yet run on a system set to English.

**Comment by MaxwelsDonc** [comment]
I run the program on my Mac, the problem are solved.

I can translate the Chinese for you 
```OSError: [WinError 123] Incorrect file name, directory name, or volume tag method. : 'tests\\:test'```
I do not know why it doesn't work on my win laptop.

**Comment by boxed** [comment]
Ah. Yea it's the colon there. Separating paths in a list on windows should be done with `;`, because `:` has a special meaning on Windows (alternate streams).

**Comment by MaxwelsDonc** [comment]
so how can I repair it? is it the problem of me or the source code of mutt?

**Comment by boxed** [comment]
Maybe both? :P 

It's honestly quite messy to support windows. You also have `\` as part of a path, which is not ok on unix systems.

**Comment by MaxwelsDonc** [comment]
ok, so the best way is to change to linux system, thanks for your helping.
