### ISSUE TITLE
How can i export all mutants?

### ISSUE THREAD

**Issue by MaxwelsDonc** [boxed/mutmut#275]
Dear Mr. Anders Hovmöller,

Hello! I am a PhD student working in software testing, and I am currently using the Mutmut framework for generating mutants. I must say that this is an excellent framework, and I am grateful for your contributions. However, I have noticed that when I run mutmut apply mutains-id, it directly modifies my original code. What I want to do is to export all the mutants generated by Mutmut to a file and rename the function names. Here is an example:
```python
def mortgage(house_value):
    prime_rate = 1
    if house_value >= 205000:
        mortgage_rate = prime_rate + 1.75
    else:
        mortgage_rate = prime_rate + 1.27
    return mortgage_rate
```
Suppose I want to generate mutants for this function. I would run mutmut run --paths-to-mutate mortgage.py, and the terminal would output the test results:` 2. Checking mutants  11/11 🎉 0 ⏰ 0 🤔 0 🙁 11 🔇 0.` Now, I need to export all the mutants to a file (let's say the file name is mortgage_mutants.py). The contents in mortgage_mutants.py should look like this:

```python
def mortgage_v1(house_value):
    ···
    
def mortgage_v2(house_value):
    ···
    ·
    ·
    ·
def mortgage_v11(house_value):
```
My questions are:
I have looked at the source code of mutmut on Github, but I have not found an interface that provides this functionality. How can I implement this feature?
I need to cite your work in my thesis. How should I do this?
Thank you for your time and contribution to the software testing community.

Best regards,
zhouzenghui

**Comment by boxed** [comment]
You can show the mutants as diffs with `mutmut show`. If you just want to talk about the different mutants in your thesis then the diff view would be better anyway as it shows the changes much more clearly.

> I need to cite your work in my thesis. How should I do this?

Hm. Interesting. I don't know honestly. My real name is listed on my github profile. How you would cite this in an academic journal is not something I know. I only have one published paper to my name and that as co-author and it was in 2004 :P

**Comment by MaxwelsDonc** [comment]
I need to conduct experiments using different mutants, and my current approach is to use `mutmut show` to see the differences between the mutants and the source code, and then make changes manually. Therefore, I think it is necessary to add the function of exporting mutants in mutmut. Perhaps I can help implement this feature after I finish my paper.

If the name on the homepage is your real name, I know how to cite this GitHub repository in my paper. When my paper is published, I will inform you in this issue. Thank you for your help.
