### ISSUE TITLE
Mutating type aliases

### ISSUE THREAD

**Issue by sobolevn** [boxed/mutmut#28]
We use `mypy` and type aliases a lot in my company.
And it works perfectly.

However, on lines like, ([full source](https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/types.py#L23)):

```python
AnyImport = Union[ast.Import, ast.ImportFrom]
```

I see a failing mutation test. And that's kind of correct, since types do not affect runtime.
```
FAILED: mutmut wemake_python_styleguide/types.py --apply --mutation "AnyImport = Union[ast.Import, ast.ImportFrom]⤑0"
```

What can be done to fix it?
1. `# pragma: no mutate` to ignore a single item. But, I guess it kind of user-unfriendly to force this pragma on all type aliases
2. also run `mypy` after (or before) the actual tests
3. automatically detect these aliases and ignore them (unsupported)

What do you think / recommend? Thanks!

**Comment by boxed** [comment]
How many of these do you have in your code? If there are just a few of them then I don't think it's so unfriendly. One could imagine having some other way to ignore lines, like a separate whitelist file (maybe even regexes?) though.

**Comment by sobolevn** [comment]
I have a lot of them. Like ~30 just in a single project.

I like the whitelist idea. But I am not sure what implementation I can suggest. Regexes seem a good idea, but this way I have to keep a consistent naming of things that I like to disable. 

And while it will work well for type aliases (one can use `*Type` as a naming pattern, or `Any*` in my case), it won't work for any other cases.

**Comment by boxed** [comment]
For the whitelist, I was thinking something that acts just like the pragma but is in a separate file. You'll have to still run the full mutation testing but then add all lines (mutants?) you want to whitelist to a .mutmut-whitelist-mutants file or something.

**Comment by boxed** [comment]
There is now a more powerful system to do whitelisting and other configuration.
