### ISSUE TITLE
Incorrect retrieval of mutation cached status

### ISSUE THREAD

**Issue by Meg4Bit** [boxed/mutmut#280]
https://github.com/boxed/mutmut/blob/53d4aa1ceeda8e3010836fddd74b7914ec516316/mutmut/cache.py#L441-L442

When there are duplicate lines in the file, the program uses cache of the first of such lines. Instead should be used _line_number_

**Comment by Meg4Bit** [comment]
But updates of line numbers occur on the early stages, meaning that the lines are up to date during read of cache.

Here are the examples, I've faced while testing Flask:
https://github.com/pallets/flask/blob/d0bf462866289ad8bfe29b6e4e1e0f531003ab34/src/flask/blueprints.py#L531
https://github.com/pallets/flask/blob/d0bf462866289ad8bfe29b6e4e1e0f531003ab34/src/flask/blueprints.py#L550

Guess that there can be other situations when lines are similar.

**Comment by boxed** [comment]
Ah. That's a good point. I'm open to a PR.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
