### ISSUE TITLE
html command missing from --help but included when no command supplied

### ISSUE THREAD

**Issue by drjasonharrison** [boxed/mutmut#283]
When executing
```
mutmut --help
```

the html command is not listed.

However, executing `mutmut` without any commands lists `html` as a possible command.

```
$ mutmut
Usage: mutmut [OPTIONS] [COMMAND] [ARGUMENT] [ARGUMENT2]
Try 'mutmut -h' for help.

Error: None is not a valid command, must be one of run, results, apply, show, junitxml, html
```

Also `html` is not described in the README.md.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
