### ISSUE TITLE
Some results missing from html report

### ISSUE THREAD

**Issue by WiredNerd** [boxed/mutmut#289]
cache.create_html_report is not sorting mutants.  

If Pony does not return them in alphabetical order, the files with module data can be overwritten multiple times.

**Comment by boxed** [comment]
Files with module data?

**Comment by WiredNerd** [comment]
The HTML files that show the differences on the survived tests.  In my case, I would have like 10 mutuations survive, but only 2 would be in the html file becasue of the order in which the tests were written.

**Comment by WiredNerd** [comment]
Submitted fix: #290

**Comment by boxed** [comment]
Reading the PR explains it heh. Thanks.

**Comment by WiredNerd** [comment]
Example index.html I got:

File | Total | Killed | % killed | Survived
-- | -- | -- | -- | --
src\pytest_sort\config.py | 95 | 77 | 81.05 | 18
src\pytest_sort\core.py | 104 | 89 | 85.58 | 15
src\pytest_sort\database.py | 66 | 54 | 81.82 | 12
src\pytest_sort\plugin.py | 28 | 2 | 7.14 | 26
src\pytest_sort\config.py | 52 | 52 | 100.00 | 0
src\pytest_sort\core.py | 42 | 39 | 92.86 | 3
src\pytest_sort\database.py | 10 | 10 | 100.00 | 0
src\pytest_sort\plugin.py | 52 | 0 | 0.00 | 52
src\pytest_sort\core.py | 3 | 1 | 33.33 | 2
src\pytest_sort\plugin.py | 1 | 0 | 0.00 | 1

and clicking on crore.py only showed the last two survived tests.

**Comment by boxed** [comment]
Yep. I merged the PR. Thanks.
