### ISSUE TITLE
the halting problem: when a mutation triggers an infinite loop

### ISSUE THREAD

**Issue by asottile** [boxed/mutmut#29]
This is the simplest case I could come up with, some timeout handling is needed it seems?

#### t.py

```python
def t(x):
    r = 0
    while x:
        r += 2 * x
        x -= 1
    return r
```

#### tests/test_t.py

```python
from t import t


def test():
    assert t(3) == 12
```

#### output

```
$ mutmut t.py 
Running tests without mutations... Done
--- starting mutation ---
6 out of 7  (t.py         x -= 1⤑0)    
```

(and then a (presumably) indefinite hang)

**Comment by boxed** [comment]
Huh. Seems check_call has a `timeout` option in Python 3.3+, I think I'll use that. It means you won't get infinite loop checking in lower python versions, but that seems like an ok tradeoff to me. With a warning message I think it's fine. What do you think?

**Comment by boxed** [comment]
Oh, and I was thinking that the timeout should be `baseline_time_elapsed * 10` to be very resistant against timing issues.

**Comment by asottile** [comment]
Seems fine to me!  The first three projects of mine I tried `mutmut` on hit this pretty quickly (each contained one of the state-machine-like loops). (another non-portable timeout mechanism is [`signal.alarm`](https://docs.python.org/3/library/signal.html#signal.alarm) -- though the `check_call` timeout is probably good enough for what I'd want 👍)

I'm also willing to hack on this if you'd like

**Comment by boxed** [comment]
I'd welcome a PR for sure. Should be just a matter of inserting an extra kwargs on the check_output call if the python version is > 3.3. 

If you haven't looked at the source for mutmut yet you'll be surprised and delighted at how super tiny the code is I think :P

**Comment by boxed** [comment]
It was super trivial and I had some time over, so I fixed this and another bug and rolled a new release. Let me know if it didn't work!
