### ISSUE TITLE
`mutmut run 5` unintuitively does not schedule if cached

### ISSUE THREAD

**Issue by eivindjahren** [boxed/mutmut#291]
When specifying one mutant to rerun, it is not queued if already in cache regardless of whether it passed it failed, just as long as it is not untested. This seems counterintuitive as the user probably has a reason to run that specific one. At the very least, there should be some way of forcing rerun by ignoring the cache.

https://github.com/boxed/mutmut/blob/8ee19e95ee7f69d374cae82e0d949d5a9dd4b578/mutmut/__init__.py#L719

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
