### ISSUE TITLE
Modifying mutmut cache directly 

### ISSUE THREAD

**Issue by cosgroveblue** [boxed/mutmut#294]
I've been using `mutmut` for mutation testing on my project, and I recently removed a specific file from my codebase. I want to ensure that references to this removed file are also gone from the `mutmut` cache without clearing the entire cache.

Is there a direct way to update the `mutmut` cache to reflect this change, without resetting the whole cache? Any guidance or best practices for this scenario would be appreciated.

**Comment by boxed** [comment]
This seems more like a bug than something the user should have to handle.

**Comment by Jacoblightning** [comment]
I think so, the cache is in sqlite3 format. You can use [DB browser for sqlite](https://sqlitebrowser.org/) to modify it.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
