### ISSUE TITLE
`mutmut show --all` flag

### ISSUE THREAD

**Issue by l0b0** [boxed/mutmut#298]
It would be useful to have some way to show all the mutants generated by mutmut, to get an idea for what has been tried during a run. Doing this manually seems like it would be a chore:

```
for class in survived killed timeout suspicious skipped untested; do
    for id in $(mutmut result-ids "$class"); do
        mutmut show "$id"
    done
done
```

Another useful variant would be to have flags for each of the classes, such as `mutmut show --survived` showing all surviving mutations.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
