### ISSUE TITLE
Mutating strings in type annotations

### ISSUE THREAD

**Issue by sobolevn** [boxed/mutmut#30]
This is a special case from #28 

I have some functions that use strings to annotate types. And this is a valid use case.
Like this example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/base.py#L65

But, `mutmut` tries to mutate this string. And tests do not fail. 
Once again, I guess I have to run `mypy` as well. But in this case it will take too long.

Maybe we can have an option to switch off mutating type annotations?

**Comment by boxed** [comment]
I fixed it. The change is rather icky, but I'll go with it for now. Thanks for the bug report!

**Comment by boxed** [comment]
I rolled a new release for this too, please give it a try!
