### ISSUE TITLE
Setting the --no-progress flag also removes output from a run.

### ISSUE THREAD

**Issue by HarmVanDerVegt** [boxed/mutmut#304]
The output of mutmut run normally contains a line with statistics like this:

KILLED 11  TIMEOUT 0  SUSPICIOUS 0  SURVIVED 7  SKIPPED 0

If a run is done with the --no-progress flag, this line disappears. Presumably because it's constantly updated by the progress indicator, normally. Can the final version of this line be part of the output if not run with a progress indicator?

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
