### ISSUE TITLE
Support new python's versions

### ISSUE THREAD

**Issue by pomponchik** [boxed/mutmut#307]
Hello!

There in README is following text:

`If you need to run mutmut on a python 2 code base use mutmut 1.5.0. Mutmut 1.9.0 is the last version to support python 3.4, 3.5 and 3.6.`

I tried to install mutmut on pythons 3.7-3.12 - it works everywhere. Could you correct the README or fix something in code if it is neccecary?

**Comment by boxed** [comment]
You just misread that. Mutmut later than 1.9.0 requires python > 3.6.
