### ISSUE TITLE
Support mutating changed lines only

### ISSUE THREAD

**Issue by NouemanKHAL** [boxed/mutmut#316]
It would be more convenient to run something like  `mutmut run --diff-only` without having to manually generate the patch file and use the `--use-patch` flag.

Some kind of wrapper on top of the `--use-patch` implementation.

Related to https://github.com/boxed/mutmut/issues/43

**Comment by boxed** [comment]
Mutmut already does this if you have run a complete mutmut round first.

**Comment by NouemanKHAL** [comment]
Is that necessary? It's not "feasible"  for large projects...

**Comment by boxed** [comment]
I guess you could argue for a command that fills the entire mutmut cache with "skipped" for all mutants. Then after that you would get the change mode automatically.

**Comment by NouemanKHAL** [comment]
I like the idea! However, does that require generating all the mutants? I assume there would be some kind of hashing mechanism to keep track of each mutant.

**Comment by boxed** [comment]
Well.. yea all the mutants are "generated" on startup in memory. Then they get IDs based on the cache db.

**Comment by NouemanKHAL** [comment]
Would be done in reasonable time in large projects?

**Comment by boxed** [comment]
I don't know what you mean by reasonable or large :) But you can try it. If you do mutmut run and suppy --test-time-base it won't run the initial test run. So as soon as you get the number of mutants starting to count up from zero it will have done this work.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. It has code to run only relevant tests, and you can point it nicely to run just mutants in certain module or functions. See the new docs.
