### ISSUE TITLE
Add support for `--test-file` to mimic `--test-dir` but for specific files.

### ISSUE THREAD

**Issue by EdgyEdgemond** [boxed/mutmut#326]
I have some large code bases that would be nice to try mutmut on, but as the test runs aren't quick, running them for all mutations is prohibitive. I can limit the tests down to a subset, but where I have a one to one mapping `test_module.py` and `module.py` it would be nice to be able to run

`mutmut run --paths-to-mutate src/module.py --test-file tests/test_module.py`

Apologies if this is somehow possible, but trying to point test-dir at a specific file still appears to run all tests.

**Comment by boxed** [comment]
You can specify the full command line in the `runner` flag. I recently did this for my own work code base:

`setup.cfg`:
```ini
[mutmut]
paths_to_mutate=dryft/planning/scheduling.py
runner=python -m pytest dryft/planning/scheduling__tests.py
```

**Comment by EdgyEdgemond** [comment]
Solves my problem.
