### ISSUE TITLE
Strange behaviour with dataclass mutation

### ISSUE THREAD

**Issue by EdgyEdgemond** [boxed/mutmut#328]
I have a dataclass that is mutated (removing the dataclass decorator) which fails tests if applied, but does not get picked up as a handled mutation. I have cleared the cache, and checked tests with the mutation applied (confirming they do in fact fail)

I've replicated a minimal example that I think points to where the problem originates, but not why it originates.

Given the following code and tests, it correctly detects the mutation and it is killed.

code.py
```
from dataclasses import dataclass

@dataclass
class MyClass:
    a: str
    b: int
```

tests/test.py
```
from .. import code

def test_my_class():
    c = code.MyClass(a="str", b=1)
```

```
2. Checking mutants
⠇ 4/4  🎉 4  ⏰ 0  🤔 0  🙁 0  🔇 0
```

But if the dataclass is used in the declaring module, then the mutation is detected as still alive.

code.py
```
from dataclasses import dataclass

@dataclass
class MyClass:
    a: str
    b: int
 
c = MyClass(a="str", b=1)
```

tests/test.py
```
from .. import code

def test_my_class():
    c = code.MyClass(a="str", b=1)
    
def test_c():
    assert code.c == code.MyClass(a="str", b=1)
```

```
2. Checking mutants
⠹ 4/4  🎉 3  ⏰ 0  🤔 0  🙁 1  🔇 0

$ mutmut show code.py
...
Survived 🙁 (1)

---- code.py (1) ----

# mutant 1
--- code.py
+++ code.py
@@ -1,7 +1,5 @@
 from dataclasses import dataclass
 
-
-@dataclass
 class MyClass:
     a: str
     b: int
```

**Comment by EdgyEdgemond** [comment]
My assumption is it doesn't detect test failure, due to the fact that the tests do not run and in fact fail to be collected (due to the invalid use of a now non dataclass object with no init)

```
____________________________________ ERROR collecting tests/test.py _____________________________________
tests/test.py:1: in <module>
    from .. import code
mycode.py:9: in <module>
    c = MyClass("str", 1)
E   TypeError: MyClass() takes no arguments
```

**Comment by boxed** [comment]
Ooh. Good catch! I had a recent similarly weird surviving mutant that clearly fails tests that I didn't have time to investigate. I bet it's this thing!

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
