### ISSUE TITLE
Confusing output with Ctrl-C

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#33]
```
% mutmut
^C
Aborted!
Running tests without mutations...
```

It should either display the "Running tests without mutations..." before (assuming it was captured?!), or without any capturing in the first place, or not at all.

Maybe that's confusing me with #31 - that I do not see the "Running tests without mutations..." in the first place?

mutmut==0.0.24 - there is no `--version` flag?!

**Comment by boxed** [comment]
Thanks for the bug report!
