### ISSUE TITLE
`--paths-to-mutate` support?

### ISSUE THREAD

**Issue by przybylop** [boxed/mutmut#339]
mutmut 2.x. had `--paths-to-mutate` argument support: https://github.com/boxed/mutmut/blob/bdd8c37e512c47d8ccf7933eba901b97da7c707a/mutmut/__main__.py#L317-L318

whereas it was removed in mutmut 3.x: https://github.com/boxed/mutmut/blob/e8e0960f45b3675ff775e2d3580956422d5698ea/mutmut/__main__.py#L150-L151

but README still mentions it:
https://github.com/boxed/mutmut/blob/e8e0960f45b3675ff775e2d3580956422d5698ea/README.rst?plain=1#L55-L59
and the error message in `guess_paths_to_mutate()` as well:
https://github.com/boxed/mutmut/blob/e8e0960f45b3675ff775e2d3580956422d5698ea/mutmut/__main__.py#L128-L131

is the argument going to be reintroduced?

**Comment by boxed** [comment]
No. Arguments for conf was a mistake I think. All the conf should always go into the conf file. 

Thanks for the heads up on the docs issue. I will fix that.

**Comment by przybylop** [comment]
Thanks for the quick response!

What about the `paths_to_mutate` argument from config file? mutmut 3.x ignores it as well

**Comment by boxed** [comment]
Oh. Well that is a mistake then. It should make good guesses, but when it fails it should read that.

**Comment by awgymer** [comment]
> It should make good guesses, but when it fails it should read that.

Would it not make more sense for it to short-circuit to the conf value if it's set, rather than fall back to it. If it's only used as a fallback it means you can't ever run `mutmut` in a repo which had e.g. a `src` folder which did *not* contain the paths to mutate

**Comment by boxed** [comment]
Sorry, yea I was sloppy with my language. The conf should override for sure.

**Comment by boxed** [comment]
Yea, that's a mistake clearly. I've pushed a fix for this on the main branch. If someone affected by this issue could try it out before I make a release that would be appreciated.

**Comment by boxed** [comment]
This is now shipped in the latest version.

**Comment by Julien-Delavisse** [comment]
Hello,

Tools like pytest, coverage, etc., allow you to filter the files to be analyzed using markers or glob patterns.
Mutmut no longer offers this option.
I imagine there are good technical reasons for this, but I find it very cumbersome.
Test mutations take a long time and aren’t always relevant depending on the part of the codebase, and I’d really like to be able to pass a glob as a parameter to select the files to mutate.
Right now, I'm looking into the possibility of creating a wrapper around mutmut to rewrite the pyproject.toml file to achieve my goal. But it's a pretty messy solution :(

Am I the only one who feels this way? :D

**Comment by Otto-AA** [comment]
Hi @Julien-Delavisse . `paths_to_mutate` is probably not what you expect it to be ( #414 ). It's intended to be directory of your source code, so mutmut knows which code it needs to copy to execute your tests afterwards. It's not intended for selecting which files are mutated.

Mutmut currently supports wildcards that filter the mutations: `mutmut run "my_module.my_function*"`. There's a "Wildcards for testing mutants" section in the docs. Is this what you need?
