### ISSUE TITLE
FileNotFoundError even though the exact command required is fed to the terminal

### ISSUE THREAD

**Issue by VincentPelletier1** [boxed/mutmut#348]
# What Was Done
- Installed mutmut via pip install mutmut (as expected).
- Attempted to run the following command:
`mutmut run --paths-to-mutate "path/to/my/test/folder" --tests-dir "path/to/my/test/dir"`

Now, the above yielded `FileNotFoundError: Could not figure out where the code to mutate is. Please specify it by adding "paths_to_mutate=code_dir" in setup.cfg to the [mutmut] section.`

I tried various adjustments:

- Providing the parameter in list format.
- Using both relative and absolute paths.
- Changing the parameter format to --paths-to-mutate="path/to/my/test/folder".
None of these attempts resolved the issue.

# The Issue
The command should work, as the paths for the test directory and source code directory are correct. However, the error mentions a configuration file, which is not clearly documented.

The documentation does reference a config file but lacks critical information:

- Where should this file be located?
- How should it be created?
- How many such files are expected?
After trial and error, I discovered that placing the config file at the project root resolved the issue. However, this information should not require guesswork.

# Closing Thoughts
I'll be direct: libraries like this have the potential for professional use. However, insufficient documentation diminishes confidence in the package.

I would like to use this package and hope that future documentation provides more actionable guidance, especially for troubleshooting and required setup.

**Comment by boxed** [comment]
> mutmut run --paths-to-mutate "path/to/my/test/folder" --tests-dir "path/to/my/test/dir"

This is not how you run mutmut 3. This is not in any of the documentation. The error message furthermore clearly tells you what to do, and you even copy pasted the error message telling you what to do. 

> The documentation does reference a config file but lacks critical information:
> Where should this file be located?

`setup.cfg` is a standard config file for Python. This is not mutmut specific. 

> However, insufficient documentation diminishes confidence in the package.

Oh come on. You didn't read the documentation for the current version OR the very clear error message.

**Comment by boxed** [comment]
I pushed a little change to the README to make this a bit clearer.

**Comment by VincentPelletier1** [comment]
Thank you for providing clearer documentation.

I do want to note that while configuration files are indeed standard, their location is not always at the project root, and it’s not uncommon for multiple config files to exist in a project.

Regarding the terminal commands, it seems the documentation I was referencing was outdated. I’ll review the updated version and test the package again. I genuinely appreciate the effort behind this package and am excited to get it working—despite sounding a bit frustrated earlier.
