### ISSUE TITLE
Output: final newline / "old line"

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#36]
With the following output there are some problems:

1. what does `old line` mean?  Should be removed or replaced with some more descriptive message (in verbose mode only?)
2. it is missing a final newline - as you can see since Zsh prints timing information in the same line
3. it displays "1484 out of 133", i.e. the count / total appears to be off.  It would be good to see what it refers to (mutations? files?)

```
% mutmut --use-coverage --runner 'python -m pytest testing/test_collection.py' src/_pytest/nodes.py
Running tests without mutations... Done
Using coverage data from .coverage file
--- starting mutation ---
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "        return self.fspath, None, \"\"⤑0"
…
old line
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "            cache = self.config.__dict__.setdefault(\"_bestrelpathcache\", {})⤑0"
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "                fspath = cache[location[0]]⤑0"                  
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "                fspath = cache[location[0]]⤑1"
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "                fspath = self.session.fspath.bestrelpath(location[0])⤑0"
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "                fspath = self.session.fspath.bestrelpath(location[0])⤑1"
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "                cache[location[0]] = fspath⤑0"
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "                cache[location[0]] = fspath⤑1"
FAILED: mutmut src/_pytest/nodes.py --apply --mutation "            location = (fspath, location[1], str(location[2]))⤑0"
1484 out of 133  (src/_pytest/nodes.py             self._location = location⤑0)                         mutmut --use-coverage --runner 'python -m pytest testing/test_collection.py'   341.91s user 16.20s system 98% cpu 6:02.87 total
```

**Comment by boxed** [comment]
I'm currently totally reworking the output to be more friendly and give more feedback to show that something is happening.

As for the mutant count going above 100%, yea, this is https://github.com/boxed/mutmut/issues/16 I think. I need to rethink that from scratch too. The cache is basically only useful for full runs as of now :(

**Comment by boxed** [comment]
All of the issues in this ticket are obsolete with the new code on master. I would love for you to give it a try! It has (I think) vastly improved UX and the cache actually works now and it's super nice.

**Comment by boxed** [comment]
I've released 1.0.0 of mutmut with the new UX. Please give it a try, I think you'll be pleasantly surprised at how much nicer it is to use.

**Comment by blueyed** [comment]
Heh, the final newlines seems to be missing still.. :)

```
2. Checking mutants
⠦ 282/282  🎉 178  ⏰ 0  🤔 6  🙁 98mutmut run --use-coverage --runner  --paths-to-mutate src/_pytest/main.py  852.13s user 46.01s system 99% cpu 15:05.49 total
```

**Comment by blueyed** [comment]
Re 3.: ah, that's the actual line being changed.. (looked like some kind of diagram to me.. :))
Could this be in diff/patch-compatible format maybe (not unified)?

**Comment by boxed** [comment]
Yea, I should probably have a standard diff format. I just felt like this was simpler and I didn't want to have some new dependency that wouldn't help much. But maybe that was a mistake.

**Comment by boxed** [comment]
Hah, of course there's a diff command in the standard library. I'll just add that. It's pretty enough.

**Comment by boxed** [comment]
1. Probably. It seems a bit messy due to the way I handle the dict synonyms option though, I might just only support that via the config file or maybe store it in the cache? Hmm.. I'll have to think about it a bit, but in general it seems a lot nicer, I just didn't find it in the docs when I was implementing this.
2. I guess. You can just pull up another terminal and print the results during execution.
3. I see you figure it out :P
4. Name? What do you mean? I don't really have names and I don't see how that would help much if I did...
5. Embarrasing! I'll fix that in 1.0.1 :P

I'll fix the missing newline at the end in 1.0.1 too.

**Comment by nedbat** [comment]
FWIW, I'm using mutmut 1.3.1, and it's still missing the final newline.  I see:
```
⠼ 154/154  🎉 150  ⏰ 0  🤔 0  🙁 4@~/lab/templite [tmp-ec480d6d36d8cec3] nedbat/fix-mutants(+2/-2) 1m4s 2 ±
```

**Comment by boxed** [comment]
Fixed again :P Thanks for the bug report.
