### ISSUE TITLE
OSError raised when waiting for pytest to finish

### ISSUE THREAD

**Issue by Etherealflux** [boxed/mutmut#37]
I checked out master/commit 63089e9 to try the new UI (pretty nice!) but ran into trouble:

mutmut appears to be waiting for a spawned process's `returncode` to be set, continually asking for a line from `stdout` until this condition holds. However, it appears that, at some point:

1. p.returncode is still None
2. stdout.readline() raises an OSError

Wrapping the readline() call in a `try/except pass` seems to fix the issue. It let the initial test run complete, and then started counting up the killed/survived totals.

Stacktrace:

```
⠙ Running...Traceback (most recent call last):
  File "/home/flux/anaconda3/bin/mutmut", line 5, in <module>
    main()
  File "/home/flux/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/flux/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/flux/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/flux/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/flux/anaconda3/lib/python3.6/site-packages/mutmut/__main__.py", line 57, in wrapper
    f(*args, **kwargs)
  File "/home/flux/anaconda3/lib/python3.6/site-packages/mutmut/__main__.py", line 236, in main
    baseline_time_elapsed = time_test_suite(swallow_output=not s, test_command=runner, using_testmon=using_testmon)
  File "/home/flux/anaconda3/lib/python3.6/site-packages/mutmut/__main__.py", line 431, in time_test_suite
    returncode = popen_streaming_output(test_command, feedback)
  File "/home/flux/anaconda3/lib/python3.6/site-packages/mutmut/__main__.py", line 306, in popen_streaming_output
    line = stdout.readline()[:-1]  # -1 to remove the newline at the end
OSError: [Errno 5] Input/output error
```

The bandaid I applied change line 306 to look like this:

```
        try:
            line = stdout.readline()[:-1]  # -1 to remove the newline at the end
        except OSError:
            pass
```

The `except` block is only hit once. `p.returncode` appears to be set properly afterwards, and the program carries on.

My Python version is `Python 3.6.5 :: Anaconda custom (64-bit)`, if that's relevant.

**Comment by boxed** [comment]
Hm.. annoying! Does it seem (based on the amount of time) that it did actually finish the entire test suite?

**Comment by boxed** [comment]
Actually I just realized this probably breaks the infinite loop detection, so this is a bigger issue!

**Comment by boxed** [comment]
The `test_timeout` test most likely fails on your system. If you could figure this out I would be very greatful, as I don't have a system that has this behavior.

**Comment by boxed** [comment]
> and if I make it go incredibly slowly with sleep, I can get a timeout

This makes me confused. The timeout is purposefully set to a crazy amount (10x baseline) so timeouts will take a very long time. But if pytest goes into a busy loop forever that should cause a timeout too I think, I don't see how adding a sleep() helps? Hmm.. actually... where do you mean you add the sleep()? mutmut or in the test?

**Comment by Etherealflux** [comment]
I was calling `sleep(1)` before each `readline`.

For the initial test run, this made it read *only* the "test session starts" line, then quit because the program exited with `0`.

For the mutated test run, this made it read around ten lines, one per second, and then get killed.

**Comment by boxed** [comment]
That's annoying :( What OS are you on? 

All this stdout catching is pretty iffy generally. There are a huge number of stackoverflow questions on this topic and people generally seem to be having random luck with a bunch of methods. This method at least works on macOS Mojave which I am running.

**Comment by Etherealflux** [comment]
I probably should've mentioned that! This is on Ubuntu 18.04.

An potential fix would be to not only kill the process on timeout, but to also interrupt the function that's polling for output. That way, even if it gets stuck on `readline()`, control could still just be yanked away completely when time runs out.

I'd try it on Windows too, but `openpty()` doesn't even work on there :frowning_face:

**Comment by boxed** [comment]
Interrupt how? You thinking a unix signal or something?

> I'd try it on Windows too, but openpty() doesn't even work on there

Hmm, yea, I know about the windows thing, but I opted to just break it and wait for a PR... the new way is just so vastly better when it works that it's a reasonable tradeoff for now.

**Comment by Etherealflux** [comment]
I'd have to look more closely (still waking up :p ), but something like [this](https://stackoverflow.com/questions/14920384/stop-code-after-time-period) would probably do the trick. I can have a proper look at it sometime later today.

Alternatively, you could also just ignore the program's output completely and just update the spinner until it quits. But I imagine you want to have the spinner update once per passed test, so that would be a bit of a visual downgrade.

**Comment by boxed** [comment]
I guess I'd be ok with a fallback to something that just updates once per checked mutant on systems where I can't get the streaming output catching to work (including windows?)...

**Comment by s-kovacevic** [comment]
OK, solving this one was quite a ride, I'll try to be as short as possible.

First of all it is a platform "issue", kind of. I tried on 2 different Ubuntu 18.04 machines both failed to run tests, tried on my Macbook Air Mojave 10.16 and it works like a charm.

Today I forked/cloned the repo (on Ubuntu), wanted to add some functionality. 
After running tests, one test failed, you guessed it, `test_timeout`. Basically checks the code @Etherealflux mentioned above.
Turns out that loop gets stuck on `readlines` and won't break from it even after I confirmed that `p.kill()` is called. What is expected is that ` OSError [Errno 5] Input/output error` is raised beacause it is trying to read from closed `fd`. What is actually happenening is it goes through the process of sleeping and then it throws an error after the sleep is done.


On ubuntu (maybe other linux distros), when `Popen` is called with `shell=True` it creates parent process:
```
/bin/sh -c python -c "import time; time.sleep(4)"
 |-  python -c "import time; time.sleep(4)"
```

When `p.kill()` or `p.terminate()` is called it kills the `p.pid` which is pid of the parent process while child process remains alive.

Meanwhile on MacOS it is just:
```
|-  python -c "import time; time.sleep(4)"
```
So `p.kill()` kills the correct process.

Quick and dirty solution is to add `'exec ' + cmd` then it works as on MacOS.
The solution I find quite elegant is to run process in a separate session and kill the entire group (in this case both processes).

```
...
    p = Popen(
        cmd,
        shell=True,
        stdout=slave,
        stderr=slave,
        start_new_session=True   # < --
    )
    stdout = os.fdopen(master)
    os.close(slave)

    start = datetime.now()

    foo = {'raise': False}

    def timeout_killer():
        while p.returncode is None:
            sleep(0.1)
            if (datetime.now() - start).total_seconds() > timeout:
                foo['raise'] = True
                os.killpg(os.getpgid(p.pid), signal.SIGKILL)  # < ---
                return
...
```

After applying this fix it works on both Ubuntu (`83 passed, 2 warnings in 12.22 seconds`) and MacOS.

@boxed what do you think? Should I make a PR?

**Comment by s-kovacevic** [comment]
@Etherealflux can you try to reproduce this with the fix applied so this can be closed.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
