### ISSUE TITLE
`mutmut --version` does not work (required argument before)

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#39]
```
% mutmut --version
Usage: mutmut [OPTIONS] COMMAND [ARGUMENT]
Try "mutmut -h" for help.

Error: Missing argument "COMMAND".
```

See https://github.com/boxed/mutmut/issues/36#issuecomment-439705476 for some suggestion to make the click integration nicer in general.. `--version` would be an option for the main "command" then.

**Comment by boxed** [comment]
Doh!

**Comment by boxed** [comment]
Fixed.

**Comment by blueyed** [comment]
Awesome, thanks.
