### ISSUE TITLE
Python 3 supported?

### ISSUE THREAD

**Issue by fniessink** [boxed/mutmut#4]
Is mutmut supposed to work with Python 3? On Mac OS X, using Python 3.6.1 I get this:
```
$ pip3 install mutmut
...
$ mutmut --help
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/mutmut", line 47
    print 'ERROR: no mutations performed. Are you sure the index is not too big?'
                                                                                ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by boxed** [comment]
Heh, well that's a bit silly of me. That's an easy fix. 

The general problem with mutmut on Python 3 is that it's based on baron, a lib which hasn't got complete Python 3 support. I think they accept PRs though.

**Comment by boxed** [comment]
Oh, just realized I just hadn't released the latest code that has this fixed already.

**Comment by fniessink** [comment]
I was just trying to see if I could create a PR, but that isn't necessary then.

**Comment by boxed** [comment]
Phew, that was harder than I'd expected. Anyway, new version of mutmut is up! Hope it works for you.

**Comment by fniessink** [comment]
Uhm, the history file seems to be missing...
```
$ pip3 install mutmut
Collecting mutmut
  Downloading mutmut-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sg/dhmz_8gd1g52c5s226lvrzlm0000gn/T/pip-build-clg75jb5/mutmut/setup.py", line 8, in <module>
        history = open('HISTORY.rst').read().replace('.. :changelog:', '')
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sg/dhmz_8gd1g52c5s226lvrzlm0000gn/T/pip-build-clg75jb5/mutmut/
```

**Comment by boxed** [comment]
All very mysterious. I wonder how I managed to publish a package last time! In any case, I've pushed a new version that now works for me. For some reason I had to nuke my local pip cache to get it to install which was weird...

**Comment by boxed** [comment]
Did you get it to work?

**Comment by fniessink** [comment]
`pip3 install -U mutmut` now works, thanks!

**Comment by boxed** [comment]
Great! Let me know how actual mutation testing goes.

**Comment by fniessink** [comment]
Unfortunately Baron doesn't support the Python 3.6 type annotation syntax that I'm using, so mutmut fails with a baron.parser.ParsingError.

**Comment by boxed** [comment]
:( 

Baron doesn't seem to be moving at all really. Such a pity because there really is no alternative.
