### ISSUE TITLE
Mutate only changes from a patch

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#43]
I think a very useful feature would be to only mutate code that has been changed in a patch (e.g. what is in the Git index etc).

This way you could run mutmut before/after committing changes to check if everything is covered with regard to mutations in a new commit (which not enforcing checks on the whole code base).

**Comment by boxed** [comment]
Depends on the purpose I guess... if you have a zero mutant project where you don't want to introduce new mutants you can already do this if you just save the .mutmut-cache file and run the changes based on it. 

What is the use case you're thinking about?

**Comment by blueyed** [comment]
The use case is having a non-zero mutant project, where you want to start eliminating mutants based on new changes.
Similar to covering a PR/commit completely with tests (i.e. diff coverage should be >= X), I would like to ensure that there are no (new) mutants.
For this mutations should get applied only to the new code (changed in the patch/diff).

**Comment by boxed** [comment]
Yea ok. In this case it should be trivial since the coverage stuff is basically this, if one can just extract the lines from the patch. Do you know an easy way to do that?

**Comment by boxed** [comment]
This has now been implemented and merged!
