### ISSUE TITLE
Wrong "No mutation performed" message while another mutation is applied

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#45]
While mutation 6107 was running I've tried `mutmut show 6106` (the last failed one), and it said "No mutation performed".

However that was likely only due to the next mutation being applied already, which touched the same code.

The below commands were run later (after 6107 finished):

```
% mutmut show 6106
--- project/app/models.py
+++ project/app/models.py
@@ -113,7 +113,7 @@
 …
-FOO = 'BAR'  # legacy
+FOO = 'XXBARXX'  # legacy
 …

% mutmut show 6107
--- project/app/models.py
+++ project/app/models.py
@@ -113,7 +113,7 @@
 …
-FOO = 'BAR'  # legacy
+FOO = None  # legacy
 …
```

This indicates that `mutmut show` goes to the actual files contents or something like that?!

**Comment by boxed** [comment]
Yea it reads the file on disk and performs the mutation in memory and then creates the diff.

**Comment by boxed** [comment]
I believe this was due to the crappy cache that didn't handle duplicate lines before. At least I'm going to hope so. If you still see this issue with 1.1.0+, please reopen this issue.
