### ISSUE TITLE
Top-down approach / applying multiple mutations at once

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#46]
I wonder if it is a good idea to apply mutants top-down, i.e. initially apply all mutants and then remove them similar to bisecting.

This would only require a single test run with all mutants enabled for a project that has no surviving mutants anymore (best case), and would continue by removing half of the mutations etc afterwards, remembering which sets of mutants were caught etc.

The idea is to have less test runs in total.

Just thinking out loud..

**Comment by boxed** [comment]
Maybe one could try to assemble some statistics on projects that have 100% coverage but has not done mutation testing and see which mutants survive. One could at least imagine applying consecutive mutations in pairs or triples initially and that could pass sometimes. 

Do you have a project where you can evaluate this possibility?

**Comment by blueyed** [comment]
Yes, but not open source.

A good example project appears to be pytest itself.

**Comment by boxed** [comment]
Do you get a lot of mutations with consecutive mutation ids? Intuitively it feels like I wouldn't want to try more than maybe tops 4 mutations in one run. 

Just having access to which specific tests to run for a specific line seems like it should help a lot more for execution speed than this proposal though. Depending on the size and speed of the test suite but still.

**Comment by blueyed** [comment]
> Just having access to which specific tests to run for a specific line seems like it should help a lot more for execution speed than this proposal though.

Yes, that would be helpful.
testmon should help here providing this.

Another quick thought: it would be good if first a set of quick tests (e.g. `-m "not db"`) could be used, and then only later the others (`-m db`) would be used for the surviving mutants.
Also knowing about which tests are more likely to kill a mutant would be good (i.e. collect information about which test killed how many mutants (although that is not complete with `-x` of course, but there then `--randomly` could help to even that out)).

**Comment by boxed** [comment]
> testmon should help here providing this.

The latest version of coverage gives you this even easier from what I've understood. I'll probably wait for that.

> Another quick thought: it would be good if first a set of quick tests (e.g. -m "not db") could be used, and then only later the others (-m db) would be used for the surviving mutants.

You can easily do that just by changing your runner to `pytest -m "not db" && pytest -m "db"`

**Comment by boxed** [comment]
I tried this in a lib I've recently mutation tested at work. I checked out the first commit where I had 100% coverage and ran mutmut:

```python
survived = {3, 4, 12, 14, 16, 17, 26, 27, 31, 34, 38, 39, 40, 43, 45, 48, 49, 52, 53, 55, 57, 59, 60, 65, 66, 70, 71, 72, 73, 74, 75, 76, 77, 78, 99, 100, 104, 105, 110, 111, 112, 113, 116, 117, 121, 129, 130, 131, 134, 135, 140, 141, 146, 147, 148, 155, 156, 159, 161, 162, 163, 164, 165, 166, 167, 168}

total_number = 179

all_mutations = list(range(total_number))

count = 0

def bisect(r):
    global count
    count += 1
    if all([x in survived for x in r]):
        return

    if len(r) == 1:
        return

    midpoint = len(r) // 2
    left = r[:midpoint]
    right = r[midpoint:]

    assert r == (left + right)

    bisect(left)
    bisect(right)


bisect(all_mutations)

print(count)
```

This gives me 323 test runs, which is a lot worse than the total of 179. So based on this it feels like this is not a viable approach unless you have just an enormous amounts of mutants. If you have no tests this approach is obviously faster since it will only run the test suite twice (once for the baseline time and then one with all mutants). But I'm assuming you want to use mutmut on something that is well tested.

**Comment by boxed** [comment]
Based on this research, I'm thinking this ticket should be closed. What do you think?

**Comment by blueyed** [comment]
Interesting, but not sure if this is really what I've meant.

It should probably try to find groups based on a smaller number / chunk first.  Bisecting like that appears to be only good for finding a specific commit/thing, but not optimizing for this use case.
However, finding the first single mutant that was killed seems to be good.

I've experimented a bit with this, but in general it takes more than the normal number of test runs.
But we should keep in mind that test runs with multiple mutants (especially the first one with all mutants applied) are much faster to fail (with `-x`), so this should be taken into account also.

**Comment by boxed** [comment]
If tests fails with multiple mutants applied then you need to split that and rerun so that it's faster probably doesn't matter much since it's slower than not running the chunk at all. 

Do you have a specific algorithm in mind that we can then try on some real examples like the one above?

**Comment by boxed** [comment]
I'll close this until we get some new idea of how to do this.
