### ISSUE TITLE
Using click's subcommands

### ISSUE THREAD

**Issue by jmdacruz** [boxed/mutmut#56]
As discussed on #55, we should add support for `click`'s subcommand feature: http://click.palletsprojects.com/en/7.x/commands/. This provides greater control on arguments for each individual command, and should be a backwards compatible change. This would also improve extensibility of the CLI.

**Comment by boxed** [comment]
I looked into it but I had some trouble making it work the way I wanted. Don't remember what the issue was though.. do you want to give it a shot?

**Comment by jmdacruz** [comment]
sure, I'll give it a try
