### ISSUE TITLE
Support for HTML reports

### ISSUE THREAD

**Issue by s-kovacevic** [boxed/mutmut#61]
While looking at mutation libraries for other languages I found out that PIT (Java) has a really nice HTML report output. I think that feature like this would make mutmut easier to grasp especially for people new to mutation testing.
Also mutmut is difficult to work with when you have a lot of mutations, like:
`mutmut show 58`
`mutmut show 59`

It seems like a lot of work, but I want to hear opinions do you guys think this would be worth doing. 
Any other ideas that would improve result reading experience are welcome.

![image](https://user-images.githubusercontent.com/10282513/50667682-b403ea80-0fba-11e9-9759-e2532c256e09.png)

![image](https://user-images.githubusercontent.com/10282513/50667514-e6611800-0fb9-11e9-9bf1-4cdbd8697cd7.png)

**Comment by boxed** [comment]
Hmm, that doesn't look _that_ nice to me :P I think we can make something nicer very simply. Should be just looping over the cache.

The big downside to me is that I won't be able to brag that mutmut is ~1000 lines of code anymore (it's already a bit over that). This is not a very significant downside :P

**Comment by nklapste** [comment]
Having reports similar to PIT would definitely meet some of my use cases with larger projects!

Maybe we should adopt HTML reports similar to other python tools. 

e.g. (`pytest-html`, the `coverage html` command, ect...)

Though I do like the simple styling of PIT :P

**Comment by s-kovacevic** [comment]
Exactly.
I am not suggesting copy and paste of PIT's report CSS @boxed, just throwing this idea of HTML report out there.

Thats why I wanted to hear some feedback. If this can help with some use case, even better, maybe good intergration with CI/CD tools, that would certanly be beneficial in my opinion.

**Comment by boxed** [comment]
Does anyone want to give this 20 minutes? Or should we wait till next time I have insomnia and I whip something up? :)

**Comment by boxed** [comment]
I have merged my pretty rough html reports and made a release.
