### ISSUE TITLE
mutmut cli doesn't work on windows

### ISSUE THREAD

**Issue by fmoor** [boxed/mutmut#7]
It appears that the mutmut command line script is just called mutmut. On windows this doesn't work. The script has to have an extension i.e. *.py. I renamed the cli to mutmut.py and this didn't work either because the cli name was now colliding with the mutmut library. Changing the name again to mutmut-cmd.py fixed the collision.

Windows 10 Enterprise
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
mutmut (0.0.3)

**Comment by boxed** [comment]
I've changed so that mutmut can be executed as a module. I think this is ok as a workaround for windows. So to be more specific you do

```
python -m mutmut
```

instead of 

```
mutmut
```
