### ISSUE TITLE
pytest output plugin

### ISSUE THREAD

**Issue by sobolevn** [boxed/mutmut#84]
Hi, @boxed! 

I am running `mutmut` on my code and it works fine. 
But, mine goal is to literally see which tests are good and which tests are bad.

So, what I suggest: let's create a `pytest` plugin that will report and save failed tests into some sort of a database/file. We will have a list of failed tests and then we can find useless tests as a result.

What do you think about this?

**Comment by boxed** [comment]
Interesting! I agree that tests that never fail during mutation testing are very likely bogus. If you run pytest with the -x flag we could also find redundant tests. 

I'm hesitant to build functionality that depends on pytest. How about a feature to add a post and pre command to mutation testing? In your case you could use it to run pytest with the xml output format and in the post step run some command to collect the xml and store it with a unique name. Then you need to write a bit of code to parse all those xml files to get the data you want. 

How does this sound?

**Comment by sobolevn** [comment]
Sounds like a plan!

**Comment by boxed** [comment]
Check out the branch I've created with this feature. It's pretty straight forward code wise, just need you to try it out and see if it does what you want.

**Comment by boxed** [comment]
Well I've merged the PR, so I'll close this. Hope this works for you!
