### ISSUE TITLE
segfault on mutmut run

### ISSUE THREAD

**Issue by Funcan** [boxed/mutmut#86]
```
$ time mutmut run
...
mutmut cache is out of date, clearing it...
1. Running tests without mutations
� Running... Done

2. Checking mutants
� 323/323  🎉 190  ⏰ 1  🤔 0  🙁 132Segmentation fault (core dumped)

real	3m27.601s
user	2m38.712s
sys	0m39.054s
```

**Comment by Funcan** [comment]
```
$ time mutmut run
...
mutmut cache is out of date, clearing it...
1. Running tests without mutations
� Running... Done

2. Checking mutants
� 323/323  🎉 190  ⏰ 1  🤔 0  🙁 132Segmentation fault (core dumped)

real	3m27.601s
user	2m38.712s
sys	0m39.054s

```

I'm not sure the easiest way to get you more info for debugging - very reproducible though.

$ python --version
Python 2.7.15rc1

**Comment by Funcan** [comment]
Never mind, traced to a bad python build in my container

**Comment by boxed** [comment]
That seems more likely than pure python code crashing python :P

Hope you get some use out of mutmut!

**Comment by wrichert** [comment]
I'm having the same issue:
![image](https://user-images.githubusercontent.com/970921/54088184-9dcc2f00-435b-11e9-850e-cbcf4b932e62.png)

My Python version is Python 2.7.10 on Mac.

**Comment by boxed** [comment]
@wrichert You should be able to apply the offending mutant on disk and run outside of mutmut. If you do `mutmut results`, you should get the IDs of all the killed mutants, so just take the one with the highest number and add one and hopefully that's the one causing a segfault. If it's not the mutant itself you can also do `mutmut run <id>` to run just one mutation and see if you can narrow down the problem that way.

Really, it shouldn't be possible for mutmut to cause a segfault, it is pure python and python really should never ever segfault itself. It has never happened to me or my colleagues in my soon 9 years of professional python development :P

**Comment by wrichert** [comment]
Thanks, @boxed! Indeed, `mutmut results` and `mutmut apply` work just fine.

**Comment by boxed** [comment]
@wrichert can you reproduce the segfault with the applied mutant on disk? Or with `mutmut run <id>`?

**Comment by wrichert** [comment]
I can reproduce it only when I delete the mutant cache and rerun `mutant run`.

**Comment by boxed** [comment]
Strange.. do you have any C extensions to python installed in the environment mutmut is installed in?

**Comment by wrichert** [comment]
The module under test imports `numpy`, `pyproj`, and various `shapely` modules. Maybe some of those cause the segfault.

**Comment by boxed** [comment]
Is the code available so I can test myself? Alternatively, can you narrow down the reproduction scenario so you can share it with me in private?

**Comment by boxed** [comment]
I'm closing this until we can get more information. Seems extremely unlikely to be related to mutmut!
