### ISSUE TITLE
Add exclude_paths_to_mutate

### ISSUE THREAD

**Issue by broxane** [boxed/mutmut#91]
Hello,
I tried mutmut on a django project, and the mutation is taking a very long time since it mutates files like migrations or admin. 
It may be an idea to add a `--omit` like in coverage, or allow `path_to_mutate` to be a list of files ?

**Comment by boxed** [comment]
paths_to_mutate is indeed a list of files and/or paths to mutate. I agree that excluding some files or directories might be more convenient and easier to configure but you should be able to get this to work as is.

**Comment by broxane** [comment]
Ok, thank you for you help and quick response :ok_hand:

**Comment by boxed** [comment]
No problem. Always good to hear people are trying mutmut! 

I'll keep this issue open as a feat request for the exclude feature.
