### ISSUE TITLE
Don't mutate *args to /args

### ISSUE THREAD

**Issue by broxane** [boxed/mutmut#96]
I have a mutant which mutate 
```python
super().__init__(*args, **kwargs)
```
in 
```python
super().__init__(/args, **kwargs)
```
It's kinda cute, but not necessary :wink:

**Comment by boxed** [comment]
Yea, that's clearly a bug. Very similar to the previous bugs we've had with import *.

**Comment by broxane** [comment]
Aha, I wish I saw this :laughing:
