### ISSUE TITLE
Mutmut should rerun tests without mutation when tests hash changes

### ISSUE THREAD

**Issue by boxed** [boxed/mutmut#99]
I've made the sloppy mistake several times now to run mutmut against broken tests, this results in mutmut marking all mutants as killed, and the only way out of this state is to remove the cache and start over. This is not a good experience.

**Comment by bk521234** [comment]
I had this happen this past week when I fudged an elastic search connection mid-run and everything was passing because my tests wouldn't pass in that state.

would it make sense to make sure the tests pass midway through, even if the tests hash has not changed?

**Comment by boxed** [comment]
Ah yes. This ticket is actually fixed on master. But yes, it's correct that mutmut should run tests once in a while to make sure not mutating still passes all tests.

**Comment by krystalgamer** [comment]
Version 2.2.0 still has this problem

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
